import { DistrictData, Product } from "@/types";

export const districts: DistrictData[] = [
  {
    id: "dhaka",
    nameEn: "Dhaka",
    nameBn: "ঢাকা",
    divisionEn: "Dhaka",
    divisionBn: "ঢাকা",
    shippingFee: 60,
    deliveryEstimateDays: "1-2 Days (24-48 Hours)",
    thanas: [
      "Dhanmondi",
      "Gulshan",
      "Banani",
      "Uttara",
      "Mirpur",
      "Mohammadpur",
      "Badda",
      "Motijheel",
      "Paltan",
      "Old Dhaka",
      "Bashundhara R/A",
    ],
  },
  {
    id: "gazipur",
    nameEn: "Gazipur",
    nameBn: "গাজীপুর",
    divisionEn: "Dhaka",
    divisionBn: "ঢাকা",
    shippingFee: 80,
    deliveryEstimateDays: "2-3 Days",
    thanas: ["Gazipur Sadar", "Tongi", "Kaliakair", "Kapasia", "Sreepur"],
  },
  {
    id: "narayanganj",
    nameEn: "Narayanganj",
    nameBn: "নারায়ণগঞ্জ",
    divisionEn: "Dhaka",
    divisionBn: "ঢাকা",
    shippingFee: 80,
    deliveryEstimateDays: "2-3 Days",
    thanas: ["Narayanganj Sadar", "Fatullah", "Siddhirganj", "Sonargaon", "Rupganj"],
  },
  {
    id: "chattogram",
    nameEn: "Chattogram",
    nameBn: "চট্টগ্রাম",
    divisionEn: "Chattogram",
    divisionBn: "চট্টগ্রাম",
    shippingFee: 120,
    deliveryEstimateDays: "2-3 Days",
    thanas: ["Agrabad", "Panchlaish", "GEC Circle", "Kotwali", "Halishahar", "Nasirabad", "Hathazari"],
  },
  {
    id: "sylhet",
    nameEn: "Sylhet",
    nameBn: "সিলেট",
    divisionEn: "Sylhet",
    divisionBn: "সিলেট",
    shippingFee: 120,
    deliveryEstimateDays: "3-4 Days",
    thanas: ["Zindabazar", "Amberkhana", "Sylhet Sadar", "Beanibazar", "Golapganj", "Shahjalal Uposhohor"],
  },
  {
    id: "rajshahi",
    nameEn: "Rajshahi",
    nameBn: "রাজশাহী",
    divisionEn: "Rajshahi",
    divisionBn: "রাজশাহী",
    shippingFee: 120,
    deliveryEstimateDays: "3-4 Days",
    thanas: ["Boalia", "Motihar", "Rajpara", "Shah Mokhdum", "Paba"],
  },
  {
    id: "khulna",
    nameEn: "Khulna",
    nameBn: "খুলনা",
    divisionEn: "Khulna",
    divisionBn: "খুলনা",
    shippingFee: 120,
    deliveryEstimateDays: "3-4 Days",
    thanas: ["Khulna Sadar", "Sonadanga", "Khalishpur", "Daulatpur", "Khan Jahan Ali"],
  },
  {
    id: "barishal",
    nameEn: "Barishal",
    nameBn: "বরিশাল",
    divisionEn: "Barishal",
    divisionBn: "বরিশাল",
    shippingFee: 120,
    deliveryEstimateDays: "3-4 Days",
    thanas: ["Kotwali", "Barishal Sadar", "Bakerganj", "Babuganj", "Gournadi"],
  },
  {
    id: "rangpur",
    nameEn: "Rangpur",
    nameBn: "রংপুর",
    divisionEn: "Rangpur",
    divisionBn: "রংপুর",
    shippingFee: 120,
    deliveryEstimateDays: "3-4 Days",
    thanas: ["Kotwali", "Rangpur Sadar", "Badarganj", "Mithapukur", "Pirgachha"],
  },
  {
    id: "cumilla",
    nameEn: "Cumilla",
    nameBn: "কুমিল্লা",
    divisionEn: "Chattogram",
    divisionBn: "চট্টগ্রাম",
    shippingFee: 110,
    deliveryEstimateDays: "2-3 Days",
    thanas: ["Kandirpar", "Cumilla Adarsha Sadar", "Laksam", "Debidwar", "Burichang"],
  },
];

export const products: Product[] = [
  {
    id: "bx-prod-001",
    titleEn: "Samsung Galaxy A55 5G (8GB/128GB) Official BD Warranty",
    titleBn: "স্যামসাং গ্যালাক্সি A55 5G (৮জিবি/১২৮জিবি) অফিসিয়াল বিডি ওয়ারেন্টি",
    slug: "samsung-galaxy-a55-5g",
    brand: "Samsung",
    category: "electronics",
    categoryBn: "ইলেকট্রনিক্স",
    subCategory: "Smartphones",
    price: 46999,
    originalPrice: 52999,
    discountPercent: 11,
    rating: 4.8,
    reviewCount: 342,
    stock: 28,
    soldCount: 184,
    isFlashDeal: true,
    flashDiscount: 15,
    isBazaarMall: true,
    isDarazPriceBeater: true,
    thumbnail: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800&auto=format&fit=crop&q=80",
    ],
    priceHistory: [
      { date: "90 days ago", price: 52999, note: "Launch Price" },
      { date: "60 days ago", price: 49999, note: "Eid Promo" },
      { date: "30 days ago", price: 48500, note: "Regular" },
      { date: "15 days ago", price: 47999, note: "Price Drop" },
      { date: "Today", price: 46999, note: "BazaarX Flash Deal (Lowest in 90D)", isLowest: true },
    ],
    descriptionEn: "Experience next-level speed and durability with Samsung Galaxy A55 5G featuring Super AMOLED display, 50MP OIS camera, and Gorilla Glass Victus+.",
    descriptionBn: "স্যামসাং গ্যালাক্সি A55 5G-তে রয়েছে সুপার AMOLED ডিসপ্লে, ৫০ মেগাপিক্সেল OIS ট্রিপল ক্যামেরা, মেটাল ফ্রেম এবং ১ বছরের অফিসিয়াল স্যামসাং বাংলাদেশ ওয়ারেন্টি।",
    keyFeaturesEn: [
      "6.6\" 120Hz Super AMOLED Display with Vision Booster",
      "50MP OIS Main Camera + 12MP Ultra-wide + 32MP Selfie",
      "5,000mAh Battery with 25W Fast Charging support",
      "IP67 Dust & Water Resistance",
      "1 Year Official Samsung Bangladesh Warranty",
    ],
    keyFeaturesBn: [
      "৬.৬ ইঞ্চি ১২০Hz সুপার AMOLED ডিসপ্লে",
      "৫০ মেগাপিক্সেল OIS ট্রিপল ক্যামেরা ও ৩২ মেগাপিক্সেল সেলফি",
      "৫,০০০mAh ব্যাটারি ও দ্রুত চার্জিং সুবিধা",
      "IP67 ধুলা ও পানি প্রতিরোধী বডি",
      "১ বছরের অফিসিয়াল স্যামসাং বাংলাদেশ ওয়ারেন্টি",
    ],
    specifications: {
      "Display": "6.6-inch FHD+ Super AMOLED 120Hz",
      "Processor": "Exynos 1480 (4nm)",
      "RAM & Storage": "8GB RAM / 128GB Internal",
      "Battery": "5000 mAh Li-Po",
      "Network": "5G, 4G LTE, Dual SIM",
      "Warranty": "1 Year Official Brand Warranty",
    },
    seller: {
      id: "sel-001",
      name: "Samsung Bangladesh Flagship Store",
      nameBn: "স্যামসাং বাংলাদেশ ফ্ল্যাগশিপ স্টোর",
      rating: 4.9,
      ratingCount: 8420,
      shipOnTime: 99,
      chatResponseRate: 99,
      isOfficialMall: true,
      tradeLicenseVerified: true,
      joinDate: "2023",
      district: "Dhaka",
    },
    reviews: [
      {
        id: "rev-101",
        author: "Tanvir Ahmed",
        district: "Dhanmondi, Dhaka",
        rating: 5,
        date: "3 days ago",
        comment: "বাজারএক্স থেকে অর্ডার করার ২৪ ঘণ্টার মধ্যে ডেলিভারি পেয়েছি। প্রোডাক্ট ১০০% অরিজিনাল এবং দাম দারাজের চেয়ে ২,০০০ টাকা কম ছিল। প্রাইস হিস্ট্রি গ্রাফ দেখে আত্মবিশ্বাসের সাথে কিনেছি!",
        verifiedPurchase: true,
        helpfulCount: 42,
      },
      {
        id: "rev-102",
        author: "Nafisa Chowdhury",
        district: "Agrabad, Chattogram",
        rating: 5,
        date: "1 week ago",
        comment: "Excellent camera and battery life. bKash payment cashback worked instantly without any friction. Delivery took only 2 days to Chittagong.",
        verifiedPurchase: true,
        helpfulCount: 29,
      },
    ],
    shipping: {
      dhakaFee: 60,
      outsideDhakaFee: 120,
      estimatedDhakaDays: "1-2 Days",
      estimatedOutsideDays: "2-3 Days",
      freeShippingThreshold: 999,
      expressDeliveryAvailable: true,
    },
    returnPolicy: {
      days: 7,
      instantWalletRefund: true,
      doorstepPickup: true,
    },
    warrantyTextEn: "1 Year Official Manufacturer Warranty",
    warrantyTextBn: "১ বছরের অফিসিয়াল ম্যানুফ্যাকচারার ওয়ারেন্টি",
  },
  {
    id: "bx-prod-002",
    titleEn: "Anker Soundcore Space One Active Noise Cancelling Headphones",
    titleBn: "অ্যাঙ্কার সাউন্ডকোর স্পেস ওয়ান অ্যাক্টিভ নয়েজ ক্যানসেলিং হেডফোন",
    slug: "anker-soundcore-space-one",
    brand: "Anker",
    category: "electronics",
    categoryBn: "ইলেকট্রনিক্স",
    subCategory: "Audio",
    price: 8850,
    originalPrice: 10500,
    discountPercent: 16,
    rating: 4.9,
    reviewCount: 189,
    stock: 19,
    soldCount: 260,
    isFlashDeal: true,
    flashDiscount: 16,
    isBazaarMall: true,
    isDarazPriceBeater: true,
    thumbnail: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80",
    ],
    priceHistory: [
      { date: "90 days ago", price: 10500 },
      { date: "60 days ago", price: 9800 },
      { date: "30 days ago", price: 9200 },
      { date: "10 days ago", price: 8950 },
      { date: "Today", price: 8850, isLowest: true, note: "All-Time Low" },
    ],
    descriptionEn: "2X stronger voice reduction, 40 hours of ANC playtime, LDAC Hi-Res Wireless Audio support, and ultra-soft rotatable earcups.",
    descriptionBn: "অ্যাঙ্কার সাউন্ডকোর স্পেস ওয়ান হেডফোনে রয়েছে ২ গুণ উন্নত অ্যাক্টিভ নয়েজ ক্যানসেলেশন, ৪০ ঘণ্টার টানা প্লেব্যাক এবং হাই-রেজ অডিও সাপোর্ট।",
    keyFeaturesEn: [
      "Adaptive Active Noise Cancelling 2.0",
      "40H ANC Playtime / 55H Standard Playtime",
      "Hi-Res Audio Wireless with LDAC",
      "Multi-point Bluetooth 5.3 connection",
      "18 Months Anker Official Warranty",
    ],
    keyFeaturesBn: [
      "এডাপ্টিভ নয়েজ ক্যানসেলেশন ২.০",
      "৪০ ঘণ্টা পর্যন্ত টানা ব্যাটারি ব্যাকআপ",
      "হাই-রেজ অডিও ও ডিপ বেস সাউন্ড",
      "একসাথে ২টি ডিভাইসে ব্লুটুথ সংযোগ",
      "১৮ মাসের অফিসিয়াল ওয়ারেন্টি",
    ],
    specifications: {
      "Driver": "40mm Customized Dynamic Drivers",
      "Playtime": "40 Hours (ANC On) / 55 Hours (ANC Off)",
      "Charging": "USB-C Fast Charge (5 min = 4 hours)",
      "Weight": "265g",
      "Warranty": "18 Months Official Warranty",
    },
    seller: {
      id: "sel-002",
      name: "Anker Bangladesh Official",
      nameBn: "অ্যাঙ্কার বাংলাদেশ অফিসিয়াল",
      rating: 4.95,
      ratingCount: 3120,
      shipOnTime: 100,
      chatResponseRate: 98,
      isOfficialMall: true,
      tradeLicenseVerified: true,
      joinDate: "2023",
      district: "Dhaka",
    },
    reviews: [
      {
        id: "rev-201",
        author: "Farhan Shakil",
        district: "Mirpur, Dhaka",
        rating: 5,
        date: "5 days ago",
        comment: "সাউন্ড কোয়ালিটি অসাধারণ! বিশেষ করে বাসে চলার সময় নয়েজ একদম বন্ধ হয়ে যায়। প্যাকেজিং ও প্রটেকশন ছিল দুর্দান্ত।",
        verifiedPurchase: true,
        helpfulCount: 18,
      },
    ],
    shipping: {
      dhakaFee: 60,
      outsideDhakaFee: 120,
      estimatedDhakaDays: "1 Day (Next Day)",
      estimatedOutsideDays: "2-3 Days",
      freeShippingThreshold: 999,
      expressDeliveryAvailable: true,
    },
    returnPolicy: {
      days: 7,
      instantWalletRefund: true,
      doorstepPickup: true,
    },
    warrantyTextEn: "18 Months Replacement Warranty",
    warrantyTextBn: "১৮ মাসের অফিসিয়াল রিপ্লেসমেন্ট ওয়ারেন্টি",
  },
  {
    id: "bx-prod-003",
    titleEn: "Premium Tangail Handloom Pure Cotton Saree (Golden Zari Border)",
    titleBn: "প্রিমিয়াম টাঙ্গাইল তাঁতের খাঁটি সুতি শাড়ি (গোল্ডেন জরি পাড়)",
    slug: "tangail-handloom-cotton-saree",
    brand: "Aarong Touch",
    category: "fashion",
    categoryBn: "ফ্যাশন",
    subCategory: "Women's Ethnic Wear",
    price: 2450,
    originalPrice: 3200,
    discountPercent: 23,
    rating: 4.7,
    reviewCount: 412,
    stock: 45,
    soldCount: 890,
    isFlashDeal: true,
    flashDiscount: 23,
    isBazaarMall: false,
    isDarazPriceBeater: true,
    thumbnail: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?w=800&auto=format&fit=crop&q=80",
    ],
    priceHistory: [
      { date: "90 days ago", price: 3200 },
      { date: "60 days ago", price: 2950 },
      { date: "30 days ago", price: 2800 },
      { date: "10 days ago", price: 2600 },
      { date: "Today", price: 2450, isLowest: true, note: "Seasonal Weavers Deal" },
    ],
    descriptionEn: "Authentic 100% fine Tangail handloom cotton saree handcrafted by master weavers with delicate golden zari embroidery border and matching unstitched blouse piece.",
    descriptionBn: "টাঙ্গাইলের ঐতিহ্যবাহী ১০০% খাঁটি সুতি তাঁতের শাড়ি। আরামদায়ক ফেব্রিক, নিখুঁত জরি সুতার কাজ এবং সাথে ম্যাচিং ব্লাউজ পিস।",
    keyFeaturesEn: [
      "100% Breathable Fine Combed Cotton",
      "Authentic Tangail Heritage Weave",
      "Length: 12 Haat (with 80cm Blouse piece)",
      "Color Fastness Guaranteed (No bleeding)",
      "Gentle Hand Wash / Machine Washable",
    ],
    keyFeaturesBn: [
      "১০০% নরম খাঁটি সুতি আরামদায়ক কাপড়",
      "ঐতিহ্যবাহী টাঙ্গাইলের নিপুন তাঁতের কাজ",
      "দৈর্ঘ্য: ১২ হাত (৮০ সেমি ব্লাউজ পিস সহ)",
      "১০০% পাকা রঙ (রং ওঠার কোনো ভয় নেই)",
      "সহজেই ঘরে ওয়াশ করা যায়",
    ],
    specifications: {
      "Fabric": "100% Pure Combed Cotton",
      "Origin": "Tangail, Bangladesh",
      "Length": "6.3 Meters with Blouse Piece",
      "Occasion": "Festive, Daily Comfort, Office",
    },
    seller: {
      id: "sel-003",
      name: "Tangail Weavers Collective",
      nameBn: "টাঙ্গাইল তাঁতি সমবায়",
      rating: 4.85,
      ratingCount: 1540,
      shipOnTime: 98,
      chatResponseRate: 95,
      isOfficialMall: false,
      tradeLicenseVerified: true,
      joinDate: "2024",
      district: "Dhaka",
    },
    reviews: [
      {
        id: "rev-301",
        author: "Rokeya Sultana",
        district: "Sylhet Sadar",
        rating: 5,
        date: "2 days ago",
        comment: "শাড়িটির কাপড়ের কোয়ালিটি অত্যন্ত চমৎকার। গরমে পরার জন্য একদম পারফেক্ট। রঙের সাথে ছবির কোনো পার্থক্য ছিল না।",
        verifiedPurchase: true,
        helpfulCount: 31,
      },
    ],
    shipping: {
      dhakaFee: 60,
      outsideDhakaFee: 120,
      estimatedDhakaDays: "1-2 Days",
      estimatedOutsideDays: "2-4 Days",
      freeShippingThreshold: 999,
      expressDeliveryAvailable: false,
    },
    returnPolicy: {
      days: 7,
      instantWalletRefund: true,
      doorstepPickup: true,
    },
    warrantyTextEn: "Color fastness guarantee",
    warrantyTextBn: "রং ও সুতার মানের গ্যারান্টি",
  },
  {
    id: "bx-prod-004",
    titleEn: "Miyako 2.8L Double Pot Electric Rice Cooker (MRC-28)",
    titleBn: "মিয়াকো ২.৮ লিটার ডাবল পট ইলেকট্রিক রাইস কুকার (MRC-28)",
    slug: "miyako-2-8l-electric-rice-cooker",
    brand: "Miyako",
    category: "homeLiving",
    categoryBn: "হোম ও লিভিং",
    subCategory: "Kitchen Appliances",
    price: 3350,
    originalPrice: 4100,
    discountPercent: 18,
    rating: 4.8,
    reviewCount: 520,
    stock: 60,
    soldCount: 1240,
    isFlashDeal: false,
    isBazaarMall: true,
    isDarazPriceBeater: true,
    thumbnail: "https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=800&auto=format&fit=crop&q=80",
    ],
    priceHistory: [
      { date: "90 days ago", price: 4100 },
      { date: "60 days ago", price: 3800 },
      { date: "30 days ago", price: 3600 },
      { date: "15 days ago", price: 3450 },
      { date: "Today", price: 3350, isLowest: true },
    ],
    descriptionEn: "Miyako 2.8L high-efficiency rice cooker with non-stick inner pot, stainless steel steamer pot, automatic warm function, and 1-year brand warranty.",
    descriptionBn: "মিয়াকো ২.৮ লিটার ডাবল পট রাইস কুকার। নন-স্টিক কোটিং, স্টেইনলেস স্টিল স্টিমার এবং অটোমেটিক ওয়ার্মিং সুবিধাযুক্ত।",
    keyFeaturesEn: [
      "2.8 Liter capacity (suitable for 5-8 persons)",
      "Double Pot (Non-stick inner pot + SS Steamer)",
      "Automatic Keep-Warm function up to 6 hours",
      "Power consumption: 1000W energy saving heating plate",
      "1 Year Official Miyako Warranty",
    ],
    keyFeaturesBn: [
      "২.৮ লিটার ধারণক্ষমতা (৫-৮ জনের রান্নার উপযোগী)",
      "ডাবল পট (১টি নন-স্টিক + ১টি স্টিলের স্টিমার)",
      "স্বয়ংক্রিয় কিপ-ওয়ার্ম প্রযুক্তি",
      "বিদ্যুৎ সাশ্রয়ী ১০০০ ওয়াট হিটিং প্লেট",
      "১ বছরের অফিসিয়াল মিয়াকো ওয়ারেন্টি",
    ],
    specifications: {
      "Capacity": "2.8 Liters",
      "Power": "1000W / 220V 50Hz",
      "Pots Included": "1 Non-stick Inner Pot + 1 SS Steamer",
      "Warranty": "1 Year Free Service Warranty",
    },
    seller: {
      id: "sel-004",
      name: "Miyako Official Flagship",
      nameBn: "মিয়াকো অফিসিয়াল ফ্ল্যাগশিপ",
      rating: 4.88,
      ratingCount: 6300,
      shipOnTime: 99,
      chatResponseRate: 97,
      isOfficialMall: true,
      tradeLicenseVerified: true,
      joinDate: "2023",
      district: "Dhaka",
    },
    reviews: [
      {
        id: "rev-401",
        author: "Monirul Islam",
        district: "Rajshahi Sadar",
        rating: 5,
        date: "1 week ago",
        comment: "ভাত খুব সুন্দর ঝরঝরে হয় এবং স্টিমারে একসাথে সবজি সেদ্ধ করা যায়। ডেলিভারি প্যাকেজিং খুব সুরক্ষিত ছিল।",
        verifiedPurchase: true,
        helpfulCount: 22,
      },
    ],
    shipping: {
      dhakaFee: 60,
      outsideDhakaFee: 120,
      estimatedDhakaDays: "1-2 Days",
      estimatedOutsideDays: "2-3 Days",
      freeShippingThreshold: 999,
      expressDeliveryAvailable: true,
    },
    returnPolicy: {
      days: 7,
      instantWalletRefund: true,
      doorstepPickup: true,
    },
    warrantyTextEn: "1 Year Official Service Warranty",
    warrantyTextBn: "১ বছরের অফিসিয়াল সার্ভিস ওয়ারেন্টি",
  },
  {
    id: "bx-prod-005",
    titleEn: "Pure Sunderbans Mustard Flower Honey (1000g Raw & Unfiltered)",
    titleBn: "খাঁটি সুন্দরবনের সরিষা ফুলের মধু (১০০০ গ্রাম অপরিশোধিত ও প্রাকৃতিক)",
    slug: "sunderbans-mustard-flower-honey-1kg",
    brand: "Khaas Food",
    category: "groceries",
    categoryBn: "মুদিখানা",
    subCategory: "Organic & Pure Foods",
    price: 950,
    originalPrice: 1200,
    discountPercent: 21,
    rating: 4.9,
    reviewCount: 680,
    stock: 120,
    soldCount: 3400,
    isFlashDeal: false,
    isBazaarMall: true,
    isDarazPriceBeater: true,
    thumbnail: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80",
    ],
    priceHistory: [
      { date: "90 days ago", price: 1200 },
      { date: "60 days ago", price: 1100 },
      { date: "30 days ago", price: 1050 },
      { date: "10 days ago", price: 990 },
      { date: "Today", price: 950, isLowest: true },
    ],
    descriptionEn: "100% natural, unprocessed raw mustard flower honey collected directly from sustainable beekeepers in Bangladesh. Lab tested zero artificial sugar.",
    descriptionBn: "১০০% খাঁটি ও অপরিশোধিত সরিষা ফুলের প্রাকৃতিক মধু। ল্যাব টেস্টে শতভাগ নির্ভেজাল প্রমাণিত। কোনো প্রকার কৃত্রিম চিনি বা কেমিক্যাল নেই।",
    keyFeaturesEn: [
      "100% Raw, Pure & Unprocessed",
      "Direct from local Bangladeshi beekeepers",
      "Lab Certified 0% added sucrose or syrup",
      "Rich in natural antioxidants & enzymes",
      "Hygienic glass jar packaging",
    ],
    keyFeaturesBn: [
      "১০০% প্রাকৃতিক ও অপরিশোধিত মধু",
      "কোনো কৃত্রিম সুগার বা প্রিজারভেটিভ নেই",
      "ল্যাব টেস্টে শতভাগ খাঁটি প্রমাণিত",
      "প্রাকৃতিক অ্যান্টিঅক্সিডেন্টে ভরপুর",
      "স্বাস্থ্যসম্মত প্রিমিয়াম কাঁচের বয়াম",
    ],
    specifications: {
      "Weight": "1000 Grams (1 KG)",
      "Source": "Mustard Bee Farms, Bangladesh",
      "Shelf Life": "24 Months",
      "Packaging": "Food Grade Glass Jar",
    },
    seller: {
      id: "sel-005",
      name: "Khaas Food Naturals",
      nameBn: "খাস ফুড ন্যাচারালস",
      rating: 4.96,
      ratingCount: 14500,
      shipOnTime: 100,
      chatResponseRate: 99,
      isOfficialMall: true,
      tradeLicenseVerified: true,
      joinDate: "2022",
      district: "Dhaka",
    },
    reviews: [
      {
        id: "rev-501",
        author: "Dr. Kazi Mahbub",
        district: "Uttara, Dhaka",
        rating: 5,
        date: "4 days ago",
        comment: "মধুর ঘনত্ব ও স্বাদ দারুণ। খাঁটি সরিষা ফুলের যে অ্যারোমা থাকে তা পুরোপুরি বিদ্যমান। নিয়মিত সকালে খাই।",
        verifiedPurchase: true,
        helpfulCount: 48,
      },
    ],
    shipping: {
      dhakaFee: 60,
      outsideDhakaFee: 120,
      estimatedDhakaDays: "1 Day",
      estimatedOutsideDays: "2-3 Days",
      freeShippingThreshold: 999,
      expressDeliveryAvailable: true,
    },
    returnPolicy: {
      days: 7,
      instantWalletRefund: true,
      doorstepPickup: true,
    },
    warrantyTextEn: "100% Purity Money-Back Guarantee",
    warrantyTextBn: "১০০% খাঁটি হওয়ার মানি-ব্যাক গ্যারান্টি",
  },
  {
    id: "bx-prod-006",
    titleEn: "Xiaomi Smart Band 8 (1.62\" AMOLED 60Hz Display)",
    titleBn: "শাওমি স্মার্ট ব্যান্ড ৮ (১.৬২\" AMOLED ৬০Hz ডিসপ্লে)",
    slug: "xiaomi-smart-band-8",
    brand: "Xiaomi",
    category: "electronics",
    categoryBn: "ইলেকট্রনিক্স",
    subCategory: "Wearables",
    price: 3650,
    originalPrice: 4500,
    discountPercent: 19,
    rating: 4.8,
    reviewCount: 310,
    stock: 50,
    soldCount: 940,
    isFlashDeal: true,
    flashDiscount: 19,
    isBazaarMall: true,
    isDarazPriceBeater: true,
    thumbnail: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&auto=format&fit=crop&q=80",
    images: [
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=800&auto=format&fit=crop&q=80",
    ],
    priceHistory: [
      { date: "90 days ago", price: 4500 },
      { date: "60 days ago", price: 4200 },
      { date: "30 days ago", price: 3950 },
      { date: "15 days ago", price: 3800 },
      { date: "Today", price: 3650, isLowest: true },
    ],
    descriptionEn: "1.62-inch high-refresh AMOLED screen, up to 16 days battery life, 150+ fitness modes, continuous SpO2 and heart rate monitoring, 5ATM water resistance.",
    descriptionBn: "শাওমি স্মার্ট ব্যান্ড ৮-এ রয়েছে ১.৬২ ইঞ্চি উজ্জ্বল AMOLED ৬০Hz ডিসপ্লে, ১৬ দিনের ব্যাটারি লাইফ এবং ১৫০+ স্পোর্টস ট্র্যাকিং মোড।",
    keyFeaturesEn: [
      "1.62\" 60Hz AMOLED Screen with Auto-Brightness",
      "Up to 16 Days Battery Life (Fast magnetic charging)",
      "150+ Sports and Workout Tracking Modes",
      "All-day SpO2, Heart Rate & Sleep Tracking",
      "5ATM Water Resistant up to 50 meters",
    ],
    keyFeaturesBn: [
      "১.৬২\" ৬০Hz ব্রাইট AMOLED ডিসপ্লে",
      "১৬ দিন পর্যন্ত দীর্ঘস্থায়ী ব্যাটারি লাইফ",
      "১৫০+ স্পোর্টস ও ফিটনেস মোড",
      "সারাদিন হার্ট রেট ও অক্সিজেন (SpO2) ট্র্যাকিং",
      "৫০ মিটার পর্যন্ত ওয়াটারপ্রুফ",
    ],
    specifications: {
      "Display": "1.62 inch AMOLED (192 x 490)",
      "Battery": "190 mAh (16 Days Typical)",
      "Sensors": "6-axis sensor, PPG heart rate, Ambient light",
      "Connectivity": "Bluetooth 5.1 BLE",
      "Warranty": "6 Months Official Warranty",
    },
    seller: {
      id: "sel-006",
      name: "Xiaomi Bangladesh Official Mall",
      nameBn: "শাওমি বাংলাদেশ অফিশিয়াল মল",
      rating: 4.92,
      ratingCount: 11200,
      shipOnTime: 99,
      chatResponseRate: 98,
      isOfficialMall: true,
      tradeLicenseVerified: true,
      joinDate: "2023",
      district: "Dhaka",
    },
    reviews: [
      {
        id: "rev-601",
        author: "Hasibul Hasan",
        district: "Khulna Sadar",
        rating: 5,
        date: "6 days ago",
        comment: "চার্জ অনেক দিন থাকে। নোটিফিকেশনগুলো বাংলায় খুব সুন্দর দেখায়। প্রোডাক্ট শতভাগ অরিজিনাল পেয়েছি।",
        verifiedPurchase: true,
        helpfulCount: 15,
      },
    ],
    shipping: {
      dhakaFee: 60,
      outsideDhakaFee: 120,
      estimatedDhakaDays: "1-2 Days",
      estimatedOutsideDays: "2-3 Days",
      freeShippingThreshold: 999,
      expressDeliveryAvailable: true,
    },
    returnPolicy: {
      days: 7,
      instantWalletRefund: true,
      doorstepPickup: true,
    },
    warrantyTextEn: "6 Months Official Brand Warranty",
    warrantyTextBn: "৬ মাসের অফিসিয়াল ব্র্যান্ড ওয়ারেন্টি",
  },
];

export const categoryList = [
  { id: "all", nameEn: "All", nameBn: "সবগুলো", icon: "Grid" },
  { id: "electronics", nameEn: "Electronics", nameBn: "ইলেকট্রনিক্স", icon: "Smartphone" },
  { id: "fashion", nameEn: "Fashion", nameBn: "ফ্যাশন", icon: "Shirt" },
  { id: "homeLiving", nameEn: "Appliances", nameBn: "হোম ও লিভিং", icon: "Tv" },
  { id: "groceries", nameEn: "Groceries", nameBn: "মুদিখানা", icon: "ShoppingBag" },
  { id: "beauty", nameEn: "Beauty", nameBn: "বিউটি", icon: "Sparkles" },
  { id: "sports", nameEn: "Sports", nameBn: "খেলাধুলা", icon: "Activity" },
];

// Exact 12 categories as specified in the prompt
export const categoryGridList = [
  { id: "electronics", nameEn: "Electronics", nameBn: "ইলেকট্রনিক্স", icon: "Smartphone", color: "bg-blue-50 text-blue-600" },
  { id: "fashion", nameEn: "Fashion", nameBn: "ফ্যাশন", icon: "Shirt", color: "bg-pink-50 text-pink-600" },
  { id: "homeLiving", nameEn: "Home & Living", nameBn: "হোম ও লিভিং", icon: "Tv", color: "bg-amber-50 text-amber-600" },
  { id: "beauty", nameEn: "Beauty", nameBn: "বিউটি", icon: "Sparkles", color: "bg-purple-50 text-purple-600" },
  { id: "sports", nameEn: "Sports", nameBn: "খেলাধুলা", icon: "Activity", color: "bg-emerald-50 text-emerald-600" },
  { id: "books", nameEn: "Books", nameBn: "বই", icon: "BookOpen", color: "bg-red-50 text-red-600" },
  { id: "groceries", nameEn: "Groceries", nameBn: "মুদিখানা", icon: "ShoppingBag", color: "bg-green-50 text-green-600" },
  { id: "toys", nameEn: "Toys", nameBn: "খেলনা", icon: "Gamepad2", color: "bg-indigo-50 text-indigo-600" },
  { id: "automotive", nameEn: "Automotive", nameBn: "অটোমোটিভ", icon: "Car", color: "bg-slate-50 text-slate-700" },
  { id: "health", nameEn: "Health", nameBn: "স্বাস্থ্য", icon: "HeartPulse", color: "bg-rose-50 text-rose-600" },
  { id: "stationery", nameEn: "Stationery", nameBn: "স্টেশনারি", icon: "PenTool", color: "bg-cyan-50 text-cyan-700" },
  { id: "pets", nameEn: "Pets", nameBn: "পোষা প্রাণী", icon: "Dog", color: "bg-orange-50 text-orange-600" },
];

// 6 Verified Brand Storefronts
export const verifiedBrands = [
  {
    id: "samsung",
    name: "Samsung",
    tagline: "Official Flagship",
    logo: "https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=120&auto=format&fit=crop&q=80",
    rating: 4.9,
  },
  {
    id: "anker",
    name: "Anker",
    tagline: "Smart Audio & Power",
    logo: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=120&auto=format&fit=crop&q=80",
    rating: 4.95,
  },
  {
    id: "aarong",
    name: "Aarong Touch",
    tagline: "Heritage Handloom",
    logo: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=120&auto=format&fit=crop&q=80",
    rating: 4.85,
  },
  {
    id: "miyako",
    name: "Miyako",
    tagline: "Kitchen Appliances",
    logo: "https://images.unsplash.com/photo-1544233726-9f1d2b27be8b?w=120&auto=format&fit=crop&q=80",
    rating: 4.88,
  },
  {
    id: "xiaomi",
    name: "Xiaomi",
    tagline: "Official BD Mall",
    logo: "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=120&auto=format&fit=crop&q=80",
    rating: 4.92,
  },
  {
    id: "khaasfood",
    name: "Khaas Food",
    tagline: "100% Pure Naturals",
    logo: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=120&auto=format&fit=crop&q=80",
    rating: 4.96,
  },
];
