import mongoose from 'mongoose';
import dns from 'dns';
import dotenv from 'dotenv';
dotenv.config();

try {
  dns.setDefaultResultOrder('ipv4first');
  dns.setServers(['8.8.8.8', '1.1.1.1', '8.8.4.4']);
} catch (e) {}

import { User } from './models/User.js';
import { Vendor } from './models/Vendor.js';
import { Category } from './models/Category.js';
import { Product } from './models/Product.js';
import { Coupon } from './models/Coupon.js';
import { Rider } from './models/Rider.js';

const seedDatabase = async () => {
  try {
    const connStr = process.env.MONGODB_URI;
    if (!connStr) throw new Error('MONGODB_URI missing');
    await mongoose.connect(connStr);
    console.log('🌱 Connected to MongoDB for seeding...');

    // Clear existing data
    await Promise.all([
      User.deleteMany({}),
      Vendor.deleteMany({}),
      Category.deleteMany({}),
      Product.deleteMany({}),
      Coupon.deleteMany({}),
      Rider.deleteMany({}),
    ]);

    console.log('🧹 Cleaned existing database collections');

    // 1. Seed Admin User
    const adminUser = await User.create({
      name: process.env.ADMIN_NAME || 'Super Admin',
      email: process.env.ADMIN_EMAIL || 'admin@shopxbd.com',
      phone: process.env.ADMIN_PHONE || '01700000000',
      password: process.env.ADMIN_PASSWORD || 'ShopXAdmin@2026',
      role: 'admin',
      isVerified: true,
      loyaltyCoins: 5000,
    });
    console.log('👑 Admin user seeded:', adminUser.email);

    // 2. Seed Vendors
    const vendorUser1 = await User.create({
      name: 'Ghorer Bazar Official',
      email: 'vendor1@ghorerbazar.com',
      phone: '01811111111',
      password: 'Password@123',
      role: 'vendor',
      isVerified: true,
    });

    const vendor1 = await Vendor.create({
      user: vendorUser1._id,
      storeName: 'Ghorer Bazar Organic Foods',
      storeSlug: 'ghorer-bazar-organic',
      description: '১০০% খাঁটি ও নির্ভেজাল গ্রামীণ খাদ্যপণ্য ও অর্গানিক ফুড আইটেম। BSTI ও BCSIR সার্টিফাইড।',
      logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=200&auto=format&fit=crop&q=60',
      banner: 'https://images.unsplash.com/photo-1506484381205-f7945653044d?w=1200&auto=format&fit=crop&q=60',
      phone: '01811111111',
      address: 'House 12, Road 4, Dhanmondi, Dhaka',
      commissionRate: 5,
      rating: 4.9,
      totalRatings: 1820,
      totalSales: 850000,
      balance: 807500,
      status: 'approved',
    });

    const vendorUser2 = await User.create({
      name: 'TechMart Global & Gadgets',
      email: 'vendor2@techmartbd.com',
      phone: '01922222222',
      password: 'Password@123',
      role: 'vendor',
      isVerified: true,
    });

    const vendor2 = await Vendor.create({
      user: vendorUser2._id,
      storeName: 'TechMart Global Hub',
      storeSlug: 'techmart-gadgets',
      description: 'Official Brand Warranty Gadgets, Apple Flagship, Sony Cameras, Laptops & Gaming Gears.',
      logo: 'https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=200&auto=format&fit=crop&q=60',
      banner: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=60',
      phone: '01922222222',
      address: 'Multiplan Center, Level 6, Elephant Road, Dhaka',
      commissionRate: 6,
      rating: 4.9,
      totalRatings: 2450,
      totalSales: 3450000,
      balance: 3243000,
      status: 'approved',
    });

    const vendorUser3 = await User.create({
      name: 'Royal Heritage Lifestyle',
      email: 'vendor3@royalheritage.com',
      phone: '01933333333',
      password: 'Password@123',
      role: 'vendor',
      isVerified: true,
    });

    const vendor3 = await Vendor.create({
      user: vendorUser3._id,
      storeName: 'Royal Heritage & Fragrance',
      storeSlug: 'royal-heritage',
      description: 'Luxury Arabian Attars, French Perfumes, Royal Panjabis & Designer Apparel.',
      logo: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=200&auto=format&fit=crop&q=60',
      banner: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=1200&auto=format&fit=crop&q=60',
      phone: '01933333333',
      address: 'Police Plaza Concord, Gulshan 1, Dhaka',
      commissionRate: 8,
      rating: 5.0,
      totalRatings: 1120,
      totalSales: 1650000,
      balance: 1518000,
      status: 'approved',
    });

    // 3. Seed Global & Local Categories
    const categoriesData = [
      {
        name: 'Organic & Pure Foods',
        banglaName: 'খাঁটি ও অর্গানিক ফুড',
        slug: 'organic-foods',
        icon: 'Leaf',
        image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=500&auto=format&fit=crop&q=60',
        order: 1,
      },
      {
        name: 'Smartphones & Tablets',
        banglaName: 'স্মার্টফোন ও ট্যাবলেট',
        slug: 'smartphones-tablets',
        icon: 'Smartphone',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=500&auto=format&fit=crop&q=60',
        order: 2,
      },
      {
        name: 'Laptops & Computers',
        banglaName: 'ল্যাপটপ ও কম্পিউটার',
        slug: 'laptops-computers',
        icon: 'Laptop',
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500&auto=format&fit=crop&q=60',
        order: 3,
      },
      {
        name: 'Smart Gadgets & Audio',
        banglaName: 'গ্যাজেট ও অডিও',
        slug: 'electronics-gadgets',
        icon: 'Headphones',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60',
        order: 4,
      },
      {
        name: 'Cameras & Drones',
        banglaName: 'ক্যামেরা ও ড্রোন',
        slug: 'cameras-drones',
        icon: 'Camera',
        image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=500&auto=format&fit=crop&q=60',
        order: 5,
      },
      {
        name: 'Gaming & Consoles',
        banglaName: 'গেমিং ও কনসোল',
        slug: 'gaming-consoles',
        icon: 'Gamepad2',
        image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=500&auto=format&fit=crop&q=60',
        order: 6,
      },
      {
        name: 'Fashion & Luxury Apparel',
        banglaName: 'ফ্যাশন ও প্রিমিয়াম পোশাক',
        slug: 'fashion-lifestyle',
        icon: 'Shirt',
        image: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=500&auto=format&fit=crop&q=60',
        order: 7,
      },
      {
        name: 'Watches & Accessories',
        banglaName: 'ঘড়ি ও অ্যাক্সেসরিজ',
        slug: 'watches-accessories',
        icon: 'Watch',
        image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=500&auto=format&fit=crop&q=60',
        order: 8,
      },
      {
        name: 'Beauty & Fragrances',
        banglaName: 'বিউটি ও রাজকীয় আতর',
        slug: 'beauty-care',
        icon: 'Sparkles',
        image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=500&auto=format&fit=crop&q=60',
        order: 9,
      },
      {
        name: 'Home & Smart Living',
        banglaName: 'হোম ও স্মার্ট অ্যাপ্লায়েন্স',
        slug: 'home-kitchen',
        icon: 'Home',
        image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=500&auto=format&fit=crop&q=60',
        order: 10,
      },
      {
        name: 'ShopX Global Imports',
        banglaName: 'গ্লোবাল ইমপোর্টেড কালেকশন',
        slug: 'global-imports',
        icon: 'Globe',
        image: 'https://images.unsplash.com/photo-1526738549149-8e07eca6c147?w=500&auto=format&fit=crop&q=60',
        order: 11,
      },
    ];

    const seededCategories = await Category.insertMany(categoriesData);
    const catMap = new Map(seededCategories.map((c) => [c.slug, c._id]));

    // 4. Seed Worldwide & Local Flagship Products (30+ High Quality Items)
    const productsData = [
      // 1. Apple iPhone 16 Pro Max
      {
        vendor: vendor2._id,
        title: 'Apple iPhone 16 Pro Max (256GB Desert Titanium) Global',
        banglaTitle: 'অ্যাপল আইফোন ১৬ প্রো ম্যাক্স (২৫৬ জিবি ডেজার্ট টাইটানিয়াম)',
        slug: 'apple-iphone-16-pro-max-256gb',
        shortDescription: 'Apple A18 Pro chip, 48MP Fusion camera, Camera Control button, Grade 5 Titanium body.',
        description: 'Experience aerospace-grade titanium design, revolutionary A18 Pro silicon, 4K 120 fps Dolby Vision video, and unmatched battery longevity.',
        banglaDescription: '১ বছর অফিসিয়াল ইন্টারন্যাশনাল অ্যাপল ওয়ারেন্টি সহ ১০০% খাঁটি ও ইনটেক সিল প্যাক।',
        category: catMap.get('smartphones-tablets'),
        categorySlug: 'smartphones-tablets',
        brand: 'Apple',
        price: 185000,
        discountPrice: 169900,
        stock: 12,
        soldCount: 88,
        sku: 'SX-IPHONE16-PM',
        images: [
          'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800&auto=format&fit=crop&q=80',
        variants: [
          {
            name: 'Storage',
            options: [
              { title: '256GB', price: 169900, stock: 8 },
              { title: '512GB', price: 195000, stock: 4 },
            ],
          },
        ],
        attributes: [
          { name: 'Processor', value: 'Apple A18 Pro (3nm)' },
          { name: 'Display', value: '6.9" Super Retina XDR OLED ProMotion' },
          { name: 'Battery', value: 'All-day battery life (Up to 33h video)' },
        ],
        tags: ['apple', 'iphone', 'iphone16', 'flagship', 'smartphone'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        flashSaleDiscountPercent: 8,
        rating: 5.0,
        numReviews: 42,
        unit: 'box',
      },

      // 2. Apple MacBook Pro 16" M3 Max
      {
        vendor: vendor2._id,
        title: 'Apple MacBook Pro 16-inch (M3 Max Chip, 36GB RAM, 1TB SSD Space Black)',
        banglaTitle: 'অ্যাপল ম্যাকবুক প্রো ১৬-ইঞ্চি (এম৩ ম্যাক্স চিপ, ৩৬ জিবি র্যাম, ১ টিবি)',
        slug: 'apple-macbook-pro-16-m3-max',
        shortDescription: '16-core CPU, 40-core GPU, Liquid Retina XDR display, up to 22 hours battery life.',
        description: 'The ultimate powerhouse laptop for software engineers, AI researchers, and 8K creative professionals.',
        category: catMap.get('laptops-computers'),
        categorySlug: 'laptops-computers',
        brand: 'Apple',
        price: 435000,
        discountPrice: 399000,
        stock: 5,
        soldCount: 19,
        sku: 'SX-MBP16-M3MAX',
        images: [
          'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'CPU', value: 'M3 Max 16-Core' },
          { name: 'RAM', value: '36GB Unified Memory' },
          { name: 'Storage', value: '1TB Ultra-Fast SSD' },
        ],
        tags: ['macbook', 'apple', 'laptop', 'developer', 'm3max'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 5.0,
        numReviews: 28,
        unit: 'piece',
      },

      // 3. Sony Alpha A7 IV Mirrorless Camera
      {
        vendor: vendor2._id,
        title: 'Sony Alpha A7 IV Full-Frame Mirrorless Camera (Body Only)',
        banglaTitle: 'সোনি আলফা এ৭ ৪ ফুল-ফ্রেম মিররলেস ক্যামেরা',
        slug: 'sony-alpha-a7-iv-camera',
        shortDescription: '33MP Exmor R sensor, 4K 60p 10-bit 4:2:2 video, real-time eye autofocus.',
        description: 'Industry-standard hybrid mirrorless camera for professional cinematic video production and commercial photography.',
        category: catMap.get('cameras-drones'),
        categorySlug: 'cameras-drones',
        brand: 'Sony',
        price: 265000,
        discountPrice: 245000,
        stock: 7,
        soldCount: 34,
        sku: 'SX-SONY-A7IV',
        images: [
          'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Sensor', value: '33MP Full-Frame BSI' },
          { name: 'Video', value: '4K 60p 10-Bit S-Cinetone' },
        ],
        tags: ['camera', 'sony', 'photography', '4k'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.9,
        numReviews: 19,
        unit: 'piece',
      },

      // 4. Sony PlayStation 5 Pro Console
      {
        vendor: vendor2._id,
        title: 'Sony PlayStation 5 Pro Console (2TB SSD Custom Edition)',
        banglaTitle: 'সোনি প্লেস্টেশন ৫ প্রো কনসোল (২ টিবি এসএসডি)',
        slug: 'sony-playstation-5-pro-console',
        shortDescription: 'Advanced Ray Tracing, PlayStation Spectral Super Resolution (PSSR), 4K 120FPS Gaming.',
        description: 'Experience next-level gaming graphics with lightning-fast load times and tactile DualSense haptic feedback.',
        category: catMap.get('gaming-consoles'),
        categorySlug: 'gaming-consoles',
        brand: 'Sony',
        price: 110000,
        discountPrice: 98000,
        stock: 10,
        soldCount: 65,
        sku: 'SX-PS5-PRO',
        images: [
          'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Storage', value: '2TB NVMe SSD' },
          { name: 'Resolution', value: '4K 120Hz / 8K Support' },
        ],
        tags: ['ps5', 'gaming', 'playstation', 'console'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        flashSaleDiscountPercent: 11,
        rating: 4.9,
        numReviews: 54,
        unit: 'box',
      },

      // 5. Samsung Galaxy S25 Ultra 5G
      {
        vendor: vendor2._id,
        title: 'Samsung Galaxy S25 Ultra 5G (12GB/512GB Titanium Gray)',
        banglaTitle: 'স্যামসাং গ্যালাক্সি এস২৫ আল্ট্রা ৫জি (১২ জিবি/৫১২ জিবি)',
        slug: 'samsung-galaxy-s25-ultra-512gb',
        shortDescription: 'Snapdragon 8 Elite, 200MP Quad Telephoto Camera, Built-in S-Pen, Galaxy AI 2.0.',
        description: 'The pinnacle of Android engineering with AI generative editing, titanium structural frame, and 5000mAh battery.',
        category: catMap.get('smartphones-tablets'),
        categorySlug: 'smartphones-tablets',
        brand: 'Samsung',
        price: 175000,
        discountPrice: 158000,
        stock: 14,
        soldCount: 92,
        sku: 'SX-S25-ULTRA',
        images: [
          'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Processor', value: 'Snapdragon 8 Elite' },
          { name: 'Camera', value: '200MP + 50MP + 50MP + 12MP' },
        ],
        tags: ['samsung', 'galaxy', 'android', 'flagship'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.9,
        numReviews: 38,
        unit: 'box',
      },

      // 6. Sundarbans Natural Raw Honey (Ghorer Bazar)
      {
        vendor: vendor1._id,
        title: 'Sundarbans Natural Raw Honey (500g)',
        banglaTitle: 'সুন্দরবনের প্রাকৃতিক চাকের মধু (৫০০ গ্রাম)',
        slug: 'sundarbans-natural-raw-honey-500g',
        shortDescription: '১০০% প্রাকৃতিক ও খাঁটি সুন্দরবনের খলিশা ফুলের কাঁচা মধু। BSTI ল্যাব টেস্টে পরীক্ষিত।',
        description: 'সুন্দরবনের গহীন অরণ্য থেকে সরাসরি সংগৃহীত খাঁটি মধু। এতে কোনো প্রকার প্রিজারভেটিভ বা চিনি মেশানো নেই। সর্দি-কাশি নিরাময়ে ও রোগ প্রতিরোধ ক্ষমতা বৃদ্ধিতে অত্যন্ত কার্যকর।',
        banglaDescription: '১০০% ক্যাশ অন ডেলিভারি এবং রিটার্ন গ্যারান্টি সহ পাচ্ছেন অরিজিনাল সুন্দরবনের মধু।',
        category: catMap.get('organic-foods'),
        categorySlug: 'organic-foods',
        brand: 'Ghorer Bazar',
        price: 850,
        discountPrice: 690,
        stock: 45,
        soldCount: 420,
        sku: 'SX-HONEY-001',
        images: [
          'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&auto=format&fit=crop&q=80',
        variants: [
          {
            name: 'Weight',
            options: [
              { title: '500g', price: 690, stock: 30 },
              { title: '1 kg', price: 1300, stock: 15 },
            ],
          },
        ],
        attributes: [
          { name: 'উৎপাদন স্থান', value: 'সুন্দরবন, সাতক্ষীরা' },
          { name: 'কোয়ালিটি', value: '১০০% খাঁটি গ্রেড-১' },
        ],
        tags: ['honey', 'organic', 'ghorerbazar', 'sundarban', 'modhu'],
        isOrganic: true,
        isFeatured: true,
        isFlashSale: true,
        flashSaleDiscountPercent: 19,
        rating: 4.9,
        numReviews: 87,
        unit: 'jar',
      },

      // 7. Cold-Pressed Pure Mustard Oil (1L)
      {
        vendor: vendor1._id,
        title: 'Cold-Pressed Pure Mustard Oil (1 Litre)',
        banglaTitle: 'কাঠের ঘানি ভাঙা খাঁটি সরিষার তেল (১ লিটার)',
        slug: 'cold-pressed-pure-mustard-oil-1l',
        shortDescription: 'ঝাঁঝালো ও ঐতিহ্যবাহী কাঠের ঘানিতে ভাঙানো খাঁটি দেশি সরিষার তেল।',
        description: 'কোনো কেমিক্যাল ছাড়াই দেশি মাঘী সরিষা থেকে প্রস্তুত। খাঁটি ঝাঁঝ এবং রান্নায় চমৎকার স্বাদ ও গন্ধ আনে।',
        category: catMap.get('organic-foods'),
        categorySlug: 'organic-foods',
        brand: 'Ghorer Bazar',
        price: 380,
        discountPrice: 320,
        stock: 60,
        soldCount: 550,
        sku: 'SX-OIL-002',
        images: [
          'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [{ name: 'প্রসেসিং', value: 'কাঠের ঘানি' }],
        tags: ['mustard-oil', 'organic', 'cooking', 'ghorerbazar'],
        isOrganic: true,
        isFeatured: true,
        isFlashSale: false,
        rating: 5.0,
        numReviews: 142,
        unit: 'litre',
      },

      // 8. Traditional Pabna Pure Cow Ghee (500g)
      {
        vendor: vendor1._id,
        title: 'Traditional Pabna Pure Cow Ghee (500g)',
        banglaTitle: 'গাওয়া ঘি খাঁটি সুগন্ধি গাভীর ঘি (৫০০ গ্রাম)',
        slug: 'traditional-pure-cow-ghee-500g',
        shortDescription: 'পাবনার খাঁটি দুধের মাখন থেকে জ্বাল দেওয়া সেরা সুবাসের খাঁটি গাওয়া ঘি।',
        description: 'গরম ভাতে কিংবা রান্নায় অতুলনীয় স্বাদ এনে দেবে আমাদের শতভাগ প্রাকৃতিক ও কেমিক্যালমুক্ত গাওয়া ঘি।',
        category: catMap.get('organic-foods'),
        categorySlug: 'organic-foods',
        brand: 'Ghorer Bazar',
        price: 950,
        discountPrice: 790,
        stock: 40,
        soldCount: 380,
        sku: 'SX-GHEE-006',
        images: [
          'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [{ name: 'উৎস', value: 'পাবনা' }],
        tags: ['ghee', 'organic', 'ghorerbazar', 'butter'],
        isOrganic: true,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.9,
        numReviews: 110,
        unit: 'jar',
      },

      // 9. Creed Aventus Eau De Parfum (100ml)
      {
        vendor: vendor3._id,
        title: 'Creed Aventus Eau De Parfum for Men (100ml Paris Original)',
        banglaTitle: 'ক্রিড অ্যাভেনটাস অরিজিনাল লাক্সারি ফ্রেঞ্চ পারফিউম (১০০ মি.লি.)',
        slug: 'creed-aventus-edp-100ml',
        shortDescription: 'Iconic masculine scent featuring notes of birch, blackcurrant, bergamot and oakmoss.',
        description: 'Crafted with master artisanal perfumery in France. The ultimate statement of luxury and enduring sophistication.',
        category: catMap.get('beauty-care'),
        categorySlug: 'beauty-care',
        brand: 'Creed Paris',
        price: 38500,
        discountPrice: 34900,
        stock: 8,
        soldCount: 45,
        sku: 'SX-CREED-AVENTUS',
        images: [
          'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Volume', value: '100ml EDP' },
          { name: 'Origin', value: 'Paris, France' },
        ],
        tags: ['perfume', 'luxury', 'creed', 'aventus', 'fragrance'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 5.0,
        numReviews: 32,
        unit: 'bottle',
      },

      // 10. Royal Arabian Dehn Al Oud Combodi (12ml)
      {
        vendor: vendor3._id,
        title: 'Royal Dehn Al Oud Combodi Aged Pure Attar (12ml)',
        banglaTitle: 'রয়্যাল কম্বোডি দেহন আল উদ শতভাগ খাঁটি সুগন্ধি আতর',
        slug: 'royal-dehn-al-oud-combodi-12ml',
        shortDescription: '১০ বছর পুরনো খাঁটি কম্বোডিয়ান আগর কাঠ থেকে ডিস্টিল করা রয়্যাল আতর।',
        description: 'কোনো অ্যালকোহল বা সিন্থেটিক কেমিক্যাল নেই। গাঢ়, মিষ্টি ও রাজকীয় দীর্ঘস্থায়ী সুবাস।',
        category: catMap.get('beauty-care'),
        categorySlug: 'beauty-care',
        brand: 'Royal Heritage',
        price: 6500,
        discountPrice: 4800,
        stock: 20,
        soldCount: 110,
        sku: 'SX-OUD-COMBODI',
        images: [
          'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [{ name: 'টাইপ', value: '১০০% পিওর নন-অ্যালকোহলিক আতর' }],
        tags: ['attar', 'oud', 'arabian', 'islamic', 'perfume'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        flashSaleDiscountPercent: 26,
        rating: 5.0,
        numReviews: 68,
        unit: 'bottle',
      },

      // 11. Nike Air Jordan 1 Retro High OG
      {
        vendor: vendor3._id,
        title: 'Nike Air Jordan 1 Retro High OG "Chicago Lost & Found"',
        banglaTitle: 'নাইকি এয়ার জর্ডান ১ রেট্রো হাই ওজি প্রিমিয়াম স্নিকার্স',
        slug: 'nike-air-jordan-1-retro-chicago',
        shortDescription: 'Legendary basketball heritage sneakers crafted with premium cracked leather and Air cushioning.',
        description: 'Authentic 100% verified collector sneaker featuring iconic varsity red and white leather colorway.',
        category: catMap.get('fashion-lifestyle'),
        categorySlug: 'fashion-lifestyle',
        brand: 'Nike',
        price: 24500,
        discountPrice: 21500,
        stock: 15,
        soldCount: 78,
        sku: 'SX-AJ1-CHICAGO',
        images: [
          'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1552346154-21d32810aba3?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80',
        variants: [
          {
            name: 'Size (EU)',
            options: [
              { title: '41', price: 21500, stock: 5 },
              { title: '42', price: 21500, stock: 6 },
              { title: '43', price: 21500, stock: 4 },
            ],
          },
        ],
        attributes: [
          { name: 'Sole', value: 'Nike Air Encapsulated Unit' },
          { name: 'Upper', value: '100% Premium Grain Leather' },
        ],
        tags: ['nike', 'sneakers', 'jordan', 'shoes', 'fashion'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.9,
        numReviews: 57,
        unit: 'pair',
      },

      // 12. Royal Embroidered Silk Festive Panjabi
      {
        vendor: vendor3._id,
        title: 'Royal Heritage Hand-Embroidered Tussar Silk Panjabi',
        banglaTitle: 'রয়্যাল হেরিটেজ হ্যান্ড-এমব্রয়ডারি তসর সিল্ক পাঞ্জাবি',
        slug: 'royal-heritage-silk-panjabi',
        shortDescription: 'ঈদুল ফিতর ও বিয়ে অনুষ্ঠানের জন্য প্রিমিয়াম তসর সিল্ক ও নিখুঁত কারুকাজ খচিত পাঞ্জাবি।',
        description: 'আভিজাত্য ও আধুনিক ফিটিংসের অপূর্ব সংমিশ্রণ। রয়্যাল গোল্ডেন বোতাম এবং প্রিমিয়াম সুতার কাজ।',
        category: catMap.get('fashion-lifestyle'),
        categorySlug: 'fashion-lifestyle',
        brand: 'Royal Heritage',
        price: 5200,
        discountPrice: 3850,
        stock: 25,
        soldCount: 160,
        sku: 'SX-PANJABI-001',
        images: [
          'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80',
        variants: [
          {
            name: 'Size',
            options: [
              { title: 'M (40)', price: 3850, stock: 10 },
              { title: 'L (42)', price: 3850, stock: 10 },
              { title: 'XL (44)', price: 3850, stock: 5 },
            ],
          },
        ],
        attributes: [{ name: 'ফ্যাব্রিক', value: 'তসর সিল্ক' }],
        tags: ['panjabi', 'silk', 'eid', 'fashion', 'men'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        flashSaleDiscountPercent: 26,
        rating: 4.9,
        numReviews: 83,
        unit: 'piece',
      },

      // 13. Dyson Supersonic Hair Dryer Nural
      {
        vendor: vendor2._id,
        title: 'Dyson Supersonic Nural Intelligent Hair Dryer (Vinca Blue)',
        banglaTitle: 'ডাইসন সুপারসনিক নিউরাল ইন্টেলিজেন্ট হেয়ার ড্রায়ার',
        slug: 'dyson-supersonic-nural-hair-dryer',
        shortDescription: 'Automatic heat control to protect scalp health and enhance hair shine with high-velocity airflow.',
        description: 'Equipped with Nural sensor technology and 5 magnetic styling attachments for salon-quality finish at home.',
        category: catMap.get('beauty-care'),
        categorySlug: 'beauty-care',
        brand: 'Dyson',
        price: 58000,
        discountPrice: 52000,
        stock: 9,
        soldCount: 31,
        sku: 'SX-DYSON-NURAL',
        images: [
          'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Motor', value: 'Dyson V9 Digital Motor' },
          { name: 'Attachments', value: '5 Styling Nozzles Included' },
        ],
        tags: ['dyson', 'hair', 'beauty', 'luxury'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 5.0,
        numReviews: 24,
        unit: 'box',
      },

      // 14. Wireless ANC TWS Earbuds Pro 2
      {
        vendor: vendor2._id,
        title: 'Wireless ANC TWS Earbuds Pro 2 with Spatial Audio',
        banglaTitle: 'একটিভ নয়েজ ক্যান্সেলেশন TWS ইয়ারবাডস প্রো ২',
        slug: 'wireless-anc-tws-earbuds-pro-2',
        shortDescription: 'Ultra-low latency gaming mode, 36-hour battery life & ENC mic for crystal clear calls.',
        description: 'Immerse in deep bass and studio sound with the latest Bluetooth 5.3 technology and touch gestures.',
        category: catMap.get('electronics-gadgets'),
        categorySlug: 'electronics-gadgets',
        brand: 'TechMart',
        price: 2490,
        discountPrice: 1750,
        stock: 30,
        soldCount: 295,
        sku: 'SX-TWS-004',
        images: [
          'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80',
        variants: [
          {
            name: 'Color',
            options: [
              { title: 'Matte Black', price: 1750, stock: 20 },
              { title: 'Pure White', price: 1750, stock: 10 },
            ],
          },
        ],
        attributes: [
          { name: 'Bluetooth', value: '5.3' },
          { name: 'Battery', value: '36 Hours Total' },
        ],
        tags: ['earbuds', 'tws', 'gadgets', 'music', 'daraz'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        flashSaleDiscountPercent: 30,
        rating: 4.8,
        numReviews: 73,
        unit: 'piece',
      },

      // 15. Smartwatch Ultra 2.0 HD Display
      {
        vendor: vendor2._id,
        title: 'Smartwatch Ultra 2.0 HD AMOLED Display with Bluetooth Calling',
        banglaTitle: 'স্মার্টওয়াচ আল্ট্রা ২.০ ব্লুটুথ কলিং ও এমোলেড ডিসপ্লে',
        slug: 'smartwatch-ultra-2-hd-display',
        shortDescription: 'Heart rate, SpO2 sensor, 100+ sports modes, waterproof zinc-alloy body.',
        description: 'Stay connected with notifications and crystal-clear loudspeaker calling directly from your wrist.',
        category: catMap.get('watches-accessories'),
        categorySlug: 'watches-accessories',
        brand: 'TechMart',
        price: 3200,
        discountPrice: 2190,
        stock: 35,
        soldCount: 380,
        sku: 'SX-WATCH-005',
        images: [
          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
        variants: [
          {
            name: 'Strap Color',
            options: [
              { title: 'Orange Ocean', price: 2190, stock: 20 },
              { title: 'Midnight Black', price: 2190, stock: 15 },
            ],
          },
        ],
        attributes: [{ name: 'Screen', value: '2.01 Inch HD AMOLED Display' }],
        tags: ['smartwatch', 'gadgets', 'watch', 'fitness'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        flashSaleDiscountPercent: 32,
        rating: 4.9,
        numReviews: 92,
        unit: 'piece',
      },

      // 16. Nespresso Vertuo Pop Coffee Machine
      {
        vendor: vendor2._id,
        title: 'Nespresso Vertuo Pop Espresso & Coffee Machine (Global Import)',
        banglaTitle: 'নেস্প্রেসো ভার্টুও পপ স্মার্ট কফি মেশিন (ইমপোর্টেড)',
        slug: 'nespresso-vertuo-pop-coffee-machine',
        shortDescription: 'One-touch coffee brewing system with Centrifusion barcode capsule extraction.',
        description: 'Enjoy café-quality crema rich espresso, double espresso, and 230ml mug coffee at the press of a button.',
        category: catMap.get('home-kitchen'),
        categorySlug: 'home-kitchen',
        brand: 'Nespresso',
        price: 24500,
        discountPrice: 21900,
        stock: 12,
        soldCount: 41,
        sku: 'SX-NESPRESSO-001',
        images: [
          'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Water Tank', value: '0.6L Capacity' },
          { name: 'Technology', value: 'Centrifusion Rapid Spin' },
        ],
        tags: ['coffee', 'nespresso', 'kitchen', 'home', 'global'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.9,
        numReviews: 29,
        unit: 'piece',
      },

      // 17. Premium Organic Chia Seeds (500g)
      {
        vendor: vendor1._id,
        title: 'Organic Mexican Chia Seeds (500g)',
        banglaTitle: 'প্রিমিয়াম অর্গানিক চিয়া সিড (৫০০ গ্রাম)',
        slug: 'organic-mexican-chia-seeds-500g',
        shortDescription: 'ওমেগা-৩ ও ফাইবারে ভরপুর সেরা মানের প্রিমিয়াম চিয়া সিড।',
        description: 'ওজন নিয়ন্ত্রণ ও হার্টের সুস্বাস্থ্য বজায় রাখতে প্রতিদিন চিয়া সিড পানীয় হিসেবে গ্রহণ করুন।',
        category: catMap.get('organic-foods'),
        categorySlug: 'organic-foods',
        brand: 'Ghorer Bazar',
        price: 550,
        discountPrice: 450,
        stock: 75,
        soldCount: 510,
        sku: 'SX-CHIA-003',
        images: [
          'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [{ name: 'উৎস', value: 'মেক্সিকো' }],
        tags: ['chia-seeds', 'diet', 'superfood', 'organic'],
        isOrganic: true,
        isFeatured: true,
        isFlashSale: true,
        flashSaleDiscountPercent: 18,
        rating: 4.8,
        numReviews: 64,
        unit: 'pack',
      },

      // 18. Royal Kashmir Saffron (2g)
      {
        vendor: vendor1._id,
        title: 'Original Kashmiri Mogra Saffron (2g Super Grade)',
        banglaTitle: 'অরিজিনাল কাশ্মীরি মোগরা খাঁটি জাফরান (২ গ্রাম)',
        slug: 'original-kashmiri-saffron-2g',
        shortDescription: '১০০% অরিজিনাল কাশ্মীরি লাল টুকটুকে খাঁটি মোগরা জাফরান।',
        description: 'দুধ, ক্ষীর, বিরিয়ানি ও ত্বকের রূপচর্চায় সেরা সুবাস ও গাঢ় রঙের জন্য শতভাগ খাঁটি জাফরান।',
        category: catMap.get('organic-foods'),
        categorySlug: 'organic-foods',
        brand: 'Ghorer Bazar',
        price: 990,
        discountPrice: 850,
        stock: 35,
        soldCount: 210,
        sku: 'SX-SAFFRON-008',
        images: [
          'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [{ name: 'গ্রেড', value: 'সুপার মোগরা' }],
        tags: ['saffron', 'zafran', 'organic', 'ghorerbazar'],
        isOrganic: true,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.9,
        numReviews: 48,
        unit: 'box',
      },

      // 19. Ergonomic Mesh High-Back Gaming & Office Chair
      {
        vendor: vendor2._id,
        title: 'Ergonomic Breathable Mesh High-Back Executive Chair with Lumbar Support',
        banglaTitle: 'হাই-ব্যাক এক্সিকিউটিভ এরগোনমিক মেশ চেয়ার লাম্বার সাপোর্ট সহ',
        slug: 'ergonomic-mesh-highback-chair',
        shortDescription: 'Adjustable 3D armrests, dynamic lumbar support, breathable mesh, 135° recline lock.',
        description: 'Designed for long hours of coding, gaming, and remote work without back strain or fatigue.',
        category: catMap.get('home-kitchen'),
        categorySlug: 'home-kitchen',
        brand: 'ShopX Home',
        price: 16500,
        discountPrice: 13800,
        stock: 18,
        soldCount: 95,
        sku: 'SX-CHAIR-001',
        images: [
          'https://images.unsplash.com/photo-1580481077195-73ab013f7b7f?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1580481077195-73ab013f7b7f?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Weight Capacity', value: '150 KG' },
          { name: 'Mechanism', value: 'Multi-lock Sync Tilt' },
        ],
        tags: ['chair', 'ergonomic', 'office', 'gaming', 'desk'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.8,
        numReviews: 52,
        unit: 'piece',
      },

      // 20. 65W GaN Fast Charger 3-Port Adapter
      {
        vendor: vendor2._id,
        title: '65W GaN Fast Charger 3-Port Quick Adapter (2x Type-C + USB)',
        banglaTitle: '৬৫ ওয়াট গ্যান ফাস্ট চার্জার ৩-পোর্ট কুইক অ্যাডাপ্টার',
        slug: '65w-gan-fast-charger-3-port',
        shortDescription: 'ল্যাপটপ, আইফোন ও অ্যান্ড্রয়েড ফোনের জন্য আল্ট্রা ফাস্ট চার্জিং টেকনোলজি।',
        description: 'GaN III চিপসেট প্রযুক্তির মাধ্যমে ফোন ও ল্যাপটপ অতিরিক্ত গরম হওয়া ছাড়াই দ্রুত চার্জ হবে।',
        category: catMap.get('electronics-gadgets'),
        categorySlug: 'electronics-gadgets',
        brand: 'TechMart',
        price: 1850,
        discountPrice: 1390,
        stock: 40,
        soldCount: 310,
        sku: 'SX-GAN-009',
        images: [
          'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [{ name: 'পাওয়ার', value: '65W PD + QC 4.0' }],
        tags: ['charger', 'gan', 'gadgets', 'fast-charging'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        flashSaleDiscountPercent: 25,
        rating: 4.8,
        numReviews: 76,
        unit: 'piece',
      },

      // 21. Anti-Theft Waterproof Laptop Backpack
      {
        vendor: vendor2._id,
        title: 'Anti-Theft Waterproof Laptop Backpack with USB Charging Port',
        banglaTitle: 'অ্যান্টি-থেফট ওয়াটারপ্রুফ ল্যাপটপ ব্যাকপ্যাক ইউএসবি পোর্ট সহ',
        slug: 'anti-theft-waterproof-laptop-backpack',
        shortDescription: '১৫.৬ ইঞ্চি ল্যাপটপ ও অফিস ট্রাভেলের জন্য প্রিমিয়াম ওয়াটারপ্রুফ ব্যাগ।',
        description: 'লুকানো চেইন, সিকিউর পাসকোড লক এবং প্রিমিয়াম কুশন প্যাডিং সমৃদ্ধ ওয়াটারপ্রুফ ফ্যাব্রিক।',
        category: catMap.get('fashion-lifestyle'),
        categorySlug: 'fashion-lifestyle',
        brand: 'ShopX Fashion',
        price: 2200,
        discountPrice: 1550,
        stock: 30,
        soldCount: 180,
        sku: 'SX-BAG-010',
        images: [
          'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80',
        variants: [
          {
            name: 'Color',
            options: [
              { title: 'Carbon Grey', price: 1550, stock: 15 },
              { title: 'Deep Black', price: 1550, stock: 15 },
            ],
          },
        ],
        attributes: [{ name: 'সাইজ', value: '15.6 Inch Laptop' }],
        tags: ['bag', 'backpack', 'laptop', 'fashion'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.9,
        numReviews: 89,
        unit: 'piece',
      },

      // 22. 2-in-1 Rechargeable Portable Electric Blender
      {
        vendor: vendor2._id,
        title: '2-in-1 Rechargeable Portable Electric Blender Cup (6-Blade Juicer)',
        banglaTitle: '২-ইন-১ রিচার্জেবল পোর্টেবল জুসার ব্লেন্ডার কাপ',
        slug: '2-in-1-rechargeable-portable-blender',
        shortDescription: 'যেকোনো জায়গায় ফ্রেশ জুস ও স্মুদি তৈরির ৬-ব্লেড ইউএসবি রিচার্জেবল ব্লেন্ডার।',
        description: 'শক্তিশালী মোটর ও ফুড গ্রেড ম্যাটেরিয়ালে তৈরি সহজে বহনযোগ্য ট্রাভেল জুসার কাপ।',
        category: catMap.get('home-kitchen'),
        categorySlug: 'home-kitchen',
        brand: 'ShopX Home',
        price: 1350,
        discountPrice: 990,
        stock: 45,
        soldCount: 340,
        sku: 'SX-BLEND-011',
        images: [
          'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [{ name: 'ক্যাপাসিটি', value: '450 ml' }],
        tags: ['blender', 'kitchen', 'home', 'gadgets'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        flashSaleDiscountPercent: 27,
        rating: 4.7,
        numReviews: 63,
        unit: 'piece',
      },

      // 23. Premium Mixed Dry Fruits & Nuts Royal Jar (500g)
      {
        vendor: vendor1._id,
        title: 'Premium Mixed Dry Fruits & Nuts Royal Jar (500g)',
        banglaTitle: 'প্রিমিয়াম রয়্যাল ড্রিম ড্রাই ফ্রুটস অ্যান্ড নাটস মিক্স (৫০০ গ্রাম)',
        slug: 'premium-mixed-dry-fruits-nuts-500g',
        shortDescription: 'কাঠবাদাম, কাজুবাদাম, পেস্তাবাদাম, আখরোট ও কিশমিশের পুষ্টিকর সুপার কম্বো।',
        description: 'দৈনিক এনার্জি ও পুষ্টির জন্য সেরা মানের প্রিমিয়াম রোস্টেড বাদাম ও ড্রাই ফ্রুটসের সুস্বাদু মিক্স।',
        category: catMap.get('organic-foods'),
        categorySlug: 'organic-foods',
        brand: 'Ghorer Bazar',
        price: 1150,
        discountPrice: 920,
        stock: 50,
        soldCount: 420,
        sku: 'SX-NUTS-007',
        images: [
          'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1596560548464-f010549b84d7?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [{ name: 'উপাদান', value: '৮টি প্রিমিয়াম ড্রাই ফ্রুটস' }],
        tags: ['nuts', 'dry-fruits', 'health', 'organic'],
        isOrganic: true,
        isFeatured: true,
        isFlashSale: true,
        flashSaleDiscountPercent: 20,
        rating: 5.0,
        numReviews: 135,
        unit: 'jar',
      },

      // 24. Keychron Q1 Pro Wireless Custom Mechanical Keyboard
      {
        vendor: vendor2._id,
        title: 'Keychron Q1 Pro Wireless QMK/VIA Custom Mechanical Keyboard (Gateron Red)',
        banglaTitle: 'কিক্রন কিউ১ প্রো কাস্টম ওয়্যারলেস মেকানিক্যাল কীবোর্ড',
        slug: 'keychron-q1-pro-wireless-keyboard',
        shortDescription: 'Full aluminum CNC body, hot-swappable switches, sound-absorbing foam, South-facing RGB.',
        description: 'The ultimate typing experience for developers and enthusiasts with customizable keymaps via VIA.',
        category: catMap.get('laptops-computers'),
        categorySlug: 'laptops-computers',
        brand: 'Keychron',
        price: 22500,
        discountPrice: 19800,
        stock: 14,
        soldCount: 62,
        sku: 'SX-KEYCHRON-Q1',
        images: [
          'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Switches', value: 'Gateron Jupiter Red (Linear)' },
          { name: 'Connectivity', value: 'Bluetooth 5.1 + Type-C' },
        ],
        tags: ['keyboard', 'mechanical', 'keychron', 'gadgets', 'gaming'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 5.0,
        numReviews: 44,
        unit: 'box',
      },

      // 25. Bose QuietComfort Ultra Wireless Headphones
      {
        vendor: vendor2._id,
        title: 'Bose QuietComfort Ultra Wireless Noise Cancelling Headphones (Smoke White)',
        banglaTitle: 'বোস কোয়াইটকমফোর্ট আল্ট্রা ওয়্যারলেস নয়েজ ক্যানসেলিং হেডফোন',
        slug: 'bose-quietcomfort-ultra-headphones',
        shortDescription: 'World-class active noise cancellation, CustomTune audio calibration, Bose Immersive Audio.',
        description: 'Luxurious plush protein leather cushions and up to 24 hours of listening bliss on a single charge.',
        category: catMap.get('electronics-gadgets'),
        categorySlug: 'electronics-gadgets',
        brand: 'Bose',
        price: 46000,
        discountPrice: 41500,
        stock: 11,
        soldCount: 52,
        sku: 'SX-BOSE-QCULTRA',
        images: [
          'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Battery', value: '24 Hours Playback' },
          { name: 'ANC', value: 'Quiet / Aware / Immersion' },
        ],
        tags: ['bose', 'headphones', 'anc', 'audio', 'music'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.9,
        numReviews: 38,
        unit: 'piece',
      },

      // 31. Pabna Pure Organic Cow Ghee (1kg)
      {
        vendor: vendor1._id,
        title: 'Pabna Pure Organic Grass-Fed Cow Ghee (1kg Glass Jar)',
        banglaTitle: 'পাবনার খাঁটি গাওয়া ঘি (১ কেজি প্রিমিয়াম কাচের জার)',
        slug: 'pabna-organic-cow-ghee-1kg',
        shortDescription: '100% Traditional Bilona Churned Pure Desi Cow Ghee with rich aroma.',
        description: 'Authentic Pabna village cow ghee, prepared using the ancient bilona method. Zero preservatives, lab tested.',
        banglaDescription: 'পাবনার ঐতিহ্যবাহী খাঁটি গাওয়া ঘি। বিসিএসআইআর ল্যাব টেস্টে ১০০% খাঁটি প্রমাণিত।',
        category: catMap.get('organic-foods'),
        categorySlug: 'organic-foods',
        brand: 'Ghorer Bazar',
        price: 2550,
        discountPrice: 2350,
        stock: 45,
        soldCount: 310,
        sku: 'GB-GHEE-1KG',
        images: [
          'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Weight', value: '1 kg' },
          { name: 'Purity', value: '100% Desi Cow Milk' },
        ],
        tags: ['ghee', 'organic', 'pabna', 'pure', 'cow-ghee'],
        isOrganic: true,
        isFeatured: true,
        isFlashSale: true,
        rating: 4.95,
        numReviews: 185,
        unit: 'kg',
      },

      // 32. Kashmiri Royal Pure Saffron (5g)
      {
        vendor: vendor1._id,
        title: 'Royal Kashmiri Mongra Pure Saffron (5g Luxury Acrylic Box)',
        banglaTitle: 'কাশ্মীরি মংগ্রা খাঁটি জাফরান (৫ গ্রাম রয়্যাল বক্স)',
        slug: 'kashmiri-mongra-pure-saffron-5g',
        shortDescription: 'Grade-A Pure Kashmiri Saffron with deep red stigmas and intense natural aroma.',
        description: 'Certified 100% pure Kashmiri Mongra kesar. Handpicked from the valleys of Pampore.',
        banglaDescription: 'কাশ্মীরের পামপোর থেকে সরাসরি সংগৃহীত সেরা গ্রেডের খাঁটি জাফরান।',
        category: catMap.get('organic-foods'),
        categorySlug: 'organic-foods',
        brand: 'ShopX Organic',
        price: 4800,
        discountPrice: 4350,
        stock: 25,
        soldCount: 92,
        sku: 'SX-SAFFRON-5G',
        images: [
          'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Grade', value: 'Mongra Super A+' },
          { name: 'Origin', value: 'Kashmir, India' },
        ],
        tags: ['saffron', 'kesar', 'organic', 'kashmir'],
        isOrganic: true,
        isFeatured: true,
        isFlashSale: false,
        rating: 5.0,
        numReviews: 74,
        unit: 'box',
      },

      // 33. Sony WH-1000XM5 ANC Headphones
      {
        vendor: vendor2._id,
        title: 'Sony WH-1000XM5 Industry Leading Noise Cancelling Wireless Headphones',
        banglaTitle: 'সোনি WH-1000XM5 ওয়্যারলেস নয়েজ ক্যানসেলিং হেডফোন',
        slug: 'sony-wh-1000xm5-wireless-headphones',
        shortDescription: 'Dual Processor V1 & QN1, 8 microphones, 30 hours battery, LDAC Hi-Res Audio.',
        description: 'Industry-leading noise cancellation optimized automatically to your wearing conditions.',
        banglaDescription: 'অফিসিয়াল ১ বছর ওয়ারেন্টি সহ প্রিমিয়াম নয়েজ ক্যানসেলিং হেডফোন।',
        category: catMap.get('electronics-gadgets'),
        categorySlug: 'electronics-gadgets',
        brand: 'Sony',
        price: 38500,
        discountPrice: 35900,
        stock: 14,
        soldCount: 68,
        sku: 'SX-SONY-XM5',
        images: [
          'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Battery', value: '30 Hours' },
          { name: 'Audio', value: 'Hi-Res LDAC' },
        ],
        tags: ['sony', 'headphones', 'anc', 'audio'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        rating: 4.9,
        numReviews: 46,
        unit: 'piece',
      },

      // 34. Apple Watch Ultra 2
      {
        vendor: vendor2._id,
        title: 'Apple Watch Ultra 2 (GPS + Cellular, 49mm Titanium)',
        banglaTitle: 'অ্যাপল ওয়াচ আল্ট্রা ২ (৪৯ মিমি টাইটানিয়াম)',
        slug: 'apple-watch-ultra-2-49mm',
        shortDescription: '3000 nits display, S9 SiP, Dual-frequency GPS, 36-hr battery, 100m water resistance.',
        description: 'The most rugged and capable Apple Watch. Designed for outdoor adventure and endurance.',
        banglaDescription: '১ বছর অ্যাপল ইন্টারন্যাশনাল অফিসিয়াল ওয়ারেন্টি সহ অরিজিনাল ইনটেক প্যাক।',
        category: catMap.get('smartphones-tablets'),
        categorySlug: 'smartphones-tablets',
        brand: 'Apple',
        price: 98000,
        discountPrice: 92500,
        stock: 8,
        soldCount: 35,
        sku: 'SX-AW-ULTRA2',
        images: [
          'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Display', value: '3000 Nits Sapphire' },
          { name: 'Battery', value: '36-72 Hours' },
        ],
        tags: ['apple', 'watch', 'ultra', 'smartwatch'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.95,
        numReviews: 29,
        unit: 'piece',
      },

      // 35. Samsung Galaxy S24 Ultra
      {
        vendor: vendor2._id,
        title: 'Samsung Galaxy S24 Ultra (512GB Titanium Black, Galaxy AI)',
        banglaTitle: 'স্যামসাং গ্যালাক্সি এস২৪ আল্ট্রা (৫১২ জিবি টাইটানিয়াম)',
        slug: 'samsung-galaxy-s24-ultra-512gb',
        shortDescription: 'Snapdragon 8 Gen 3, 200MP Quad Tele Camera, Built-in S Pen, Galaxy AI Suite.',
        description: 'Titanium armor with flat 6.8-inch Dynamic AMOLED 2X display and revolutionary Galaxy AI tools.',
        banglaDescription: '১ বছরের অফিসিয়াল স্যামসাং ওয়ারেন্টি ও ইনস্ট্যান্ট ক্যাশ অন ডেলিভারি।',
        category: catMap.get('smartphones-tablets'),
        categorySlug: 'smartphones-tablets',
        brand: 'Samsung',
        price: 165000,
        discountPrice: 154900,
        stock: 9,
        soldCount: 54,
        sku: 'SX-SAM-S24U',
        images: [
          'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Processor', value: 'Snapdragon 8 Gen 3' },
          { name: 'Camera', value: '200MP + 50MP Periscope' },
        ],
        tags: ['samsung', 's24', 'galaxy', 'smartphone'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.88,
        numReviews: 42,
        unit: 'piece',
      },

      // 36. Philips Digital Airfryer XXL
      {
        vendor: vendor2._id,
        title: 'Philips Premium Digital Airfryer XXL (7.2L Smart Sensing Technology)',
        banglaTitle: 'ফিলিপস প্রিমিয়াম ডিজিটাল এয়ার ফ্রায়ার XXL (৭.২ লিটার)',
        slug: 'philips-premium-airfryer-xxl-7l',
        shortDescription: 'Fat Removal Technology, 90% less oil, Digital Touchscreen with presets.',
        description: 'Cook for the whole family with rapid air technology. Crispy taste with up to 90% less fat.',
        banglaDescription: 'পরিবারের স্বাস্থ্যসম্মত রান্নার জন্য ফিলিপসের অরিজিনাল এয়ার ফ্রায়ার। ২ বছরের ওয়ারেন্টি।',
        category: catMap.get('home-kitchen'),
        categorySlug: 'home-kitchen',
        brand: 'Philips',
        price: 28500,
        discountPrice: 25900,
        stock: 18,
        soldCount: 78,
        sku: 'SX-PHILIPS-AIRXXL',
        images: [
          'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Capacity', value: '7.2 Liters' },
          { name: 'Power', value: '2225 Watts' },
        ],
        tags: ['philips', 'airfryer', 'kitchen', 'home'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        rating: 4.92,
        numReviews: 61,
        unit: 'piece',
      },

      // 37. Royal Dehn Al Oud Cambodi Attar
      {
        vendor: vendor3._id,
        title: 'Royal Dehn Al Oud Cambodi Aged Arabic Pure Attar (6ml Crystal Bottle)',
        banglaTitle: 'রয়্যাল দেহন আল উদ কম্বোডি খাঁটি এরাবিক আতর (৬ মিলি)',
        slug: 'royal-dehn-al-oud-cambodi-6ml',
        shortDescription: '15-Year Aged wild Cambodian Agarwood pure non-alcoholic perfume oil.',
        description: 'Luxurious, deep woody fragrance with royal sillage that lasts over 48 hours.',
        banglaDescription: '১৫ বছরের পুরোনো খাঁটি কম্বোডিয়ান আগরউড থেকে তৈরি ১০০% অ্যালকোহলমুক্ত রাজকীয় আতর।',
        category: catMap.get('beauty-care'),
        categorySlug: 'beauty-care',
        brand: 'Royal Heritage',
        price: 9500,
        discountPrice: 8200,
        stock: 20,
        soldCount: 88,
        sku: 'RH-OUD-CAMBODI-6ML',
        images: [
          'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Longevity', value: '48+ Hours' },
          { name: 'Alcohol', value: '0% Pure Oil' },
        ],
        tags: ['attar', 'oud', 'cambodi', 'perfume', 'luxury'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 5.0,
        numReviews: 53,
        unit: 'bottle',
      },

      // 38. Premium Silk Designer Panjabi
      {
        vendor: vendor3._id,
        title: 'Royal Heritage Luxury Silk Embroidered Designer Panjabi Set',
        banglaTitle: 'রয়্যাল হেরিটেজ লাক্সারি সিল্ক এমব্রয়ডারি ডিজাইনার পাঞ্জাবি',
        slug: 'royal-heritage-silk-panjabi-set',
        shortDescription: 'Semi-Pure Silk fabric with delicate collar embroidery and matching pajama.',
        description: 'Exquisite Eid and wedding wear collection tailored with premium silk blend for unmatched elegance.',
        banglaDescription: 'ঈদ ও স্পেশাল অকেশনের জন্য খাঁটি সিল্ক ব্লেন্ডে তৈরি প্রিমিয়াম ডিজাইনার পাঞ্জাবি।',
        category: catMap.get('fashion-lifestyle'),
        categorySlug: 'fashion-lifestyle',
        brand: 'Royal Heritage',
        price: 5200,
        discountPrice: 4450,
        stock: 30,
        soldCount: 145,
        sku: 'RH-PANJABI-SILK',
        images: [
          'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800&auto=format&fit=crop&q=80',
        variants: [
          {
            name: 'Size',
            options: [
              { title: '40', price: 4450, stock: 10 },
              { title: '42', price: 4450, stock: 12 },
              { title: '44', price: 4450, stock: 8 },
            ],
          },
        ],
        attributes: [
          { name: 'Fabric', value: 'Semi-Pure Silk' },
          { name: 'Fitting', value: 'Slim Fit' },
        ],
        tags: ['panjabi', 'silk', 'eid', 'fashion', 'men'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        rating: 4.9,
        numReviews: 95,
        unit: 'set',
      },

      // 39. DJI Mini 4 Pro Fly More Combo Plus Drone
      {
        vendor: vendor2._id,
        title: 'DJI Mini 4 Pro Fly More Combo Plus Drone with RC 2 Controller',
        banglaTitle: 'ডিজেআই মিনি ৪ প্রো ফ্লাই মোর কম্বো প্লাস ড্রোন (আরসি ২ স্ক্রিন সহ)',
        slug: 'dji-mini-4-pro-fly-more-combo-plus',
        shortDescription: 'Under 249g, 4K/60fps HDR True Vertical Shooting, Omnidirectional Obstacle Sensing, 45-min Flight.',
        description: 'The premier ultralight camera drone engineered for professional cinematographers and content creators with 20km FHD video transmission.',
        banglaDescription: '১ বছর গ্লোবাল ওয়ারেন্টি সহ ডিজেআই এর সেরা আল্ট্রালাইট ৪K সিনেমাটিক ক্যামেরা ড্রোন।',
        category: catMap.get('cameras-drones'),
        categorySlug: 'cameras-drones',
        brand: 'DJI',
        price: 128000,
        discountPrice: 119500,
        stock: 8,
        soldCount: 42,
        sku: 'DJI-MINI4P-FMC',
        images: [
          'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1508614589041-895b88991e3e?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Flight Time', value: '45 mins (Plus Battery)' },
          { name: 'Video Resolution', value: '4K/60fps HDR & 4K/100fps Slow-mo' },
          { name: 'Obstacle Sensing', value: 'Omnidirectional ActiveTrack 360°' },
        ],
        tags: ['dji', 'drone', 'mini4pro', 'camera', '4k', 'aerial'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        rating: 4.95,
        numReviews: 38,
        unit: 'box',
      },

      // 40. Sony Alpha 7 IV Full-Frame Mirrorless Camera
      {
        vendor: vendor2._id,
        title: 'Sony Alpha 7 IV Full-Frame Hybrid Mirrorless Camera Body',
        banglaTitle: 'সনি আলফা ৭ IV ফুল-ফ্রেম হাইব্রিড মিররলেস ক্যামেরা বডি',
        slug: 'sony-alpha-7-iv-mirrorless-camera',
        shortDescription: '33MP Exmor R CMOS Sensor, BIONZ XR Processor, 4K 60p 10-Bit 4:2:2, Real-time Eye AF.',
        description: 'Benchmark hybrid creator tool designed for stunning still imagery and cinematic 4K video recording with cutting-edge autofocus.',
        banglaDescription: 'সনি বাংলাদেশ অফিশিয়াল অথোরাইজড ইনটেক বডি সাথে ৩ বছরের ইন্টারন্যাশনাল পার্টস ও সার্ভিস সাপোর্ট।',
        category: catMap.get('cameras-drones'),
        categorySlug: 'cameras-drones',
        brand: 'Sony',
        price: 245000,
        discountPrice: 228000,
        stock: 6,
        soldCount: 29,
        sku: 'SONY-A7M4-BODY',
        images: [
          'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
          'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Sensor', value: '33MP Full-Frame Exmor R CMOS' },
          { name: 'Video', value: '4K 60p 10-bit 4:2:2 All-Intra' },
          { name: 'Autofocus', value: '759 AF points with Real-time Eye AF' },
        ],
        tags: ['sony', 'alpha', 'a7iv', 'camera', 'fullframe', 'cinematic'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.98,
        numReviews: 47,
        unit: 'box',
      },

      // 41. Sony PlayStation 5 Pro Console
      {
        vendor: vendor2._id,
        title: 'Sony PlayStation 5 Pro Console 2TB SSD (PSSR AI Upscaling Edition)',
        banglaTitle: 'সনি প্লেস্টেশন ৫ প্রো কনসোল ২ টিবি এসএসডি (পিএসএসআর এআই আপস্কেলিং)',
        slug: 'sony-playstation-5-pro-2tb',
        shortDescription: 'Advanced Ray Tracing, PlayStation Spectral Super Resolution (PSSR), 60FPS Fidelity, 2TB SSD.',
        description: 'The pinnacle of console gaming hardware featuring upgraded GPU with 67% more compute units and AI neural upscaling.',
        banglaDescription: 'লেটেস্ট পিএস৫ প্রো এডিশন ২ টিবি আল্ট্রা-ফাস্ট এসএসডি এবং ১টি ডুয়েলসেন্স ওয়্যারলেস কন্ট্রোলার সহ।',
        category: catMap.get('gaming-consoles'),
        categorySlug: 'gaming-consoles',
        brand: 'Sony PlayStation',
        price: 105000,
        discountPrice: 94900,
        stock: 10,
        soldCount: 65,
        sku: 'PS5-PRO-2TB-ED',
        images: [
          'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Storage', value: '2TB Custom High-Speed NVMe SSD' },
          { name: 'GPU Architecture', value: 'RDNA 3 Upgraded Compute Units' },
          { name: 'Resolution Support', value: 'Native 4K 60/120Hz & 8K Support' },
        ],
        tags: ['ps5', 'ps5pro', 'playstation', 'gaming', 'console', 'sony'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        rating: 4.94,
        numReviews: 82,
        unit: 'box',
      },

      // 42. Nintendo Switch OLED Model
      {
        vendor: vendor2._id,
        title: 'Nintendo Switch OLED Model with White Joy-Con (64GB Storage)',
        banglaTitle: 'নিনটেন্ডো সুইচ ওলেড মডেল (হোয়াইট জয়-কন সহ)',
        slug: 'nintendo-switch-oled-white',
        shortDescription: '7.0-inch OLED screen, wide adjustable stand, wired LAN dock, 64 GB internal storage, enhanced audio.',
        description: 'Vibrant 7-inch OLED screen brings portable and TV gaming to life with deep blacks and punchy contrast.',
        banglaDescription: 'অন-দ্য-গো পোর্টেবল ও টিভি গেমিংয়ের জন্য পারফেক্ট ওলেড ডিসপ্লে সমৃদ্ধ কনসোল।',
        category: catMap.get('gaming-consoles'),
        categorySlug: 'gaming-consoles',
        brand: 'Nintendo',
        price: 36500,
        discountPrice: 32800,
        stock: 15,
        soldCount: 94,
        sku: 'NIN-SWITCH-OLED-WHT',
        images: [
          'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Screen', value: '7.0-inch OLED Multi-touch Screen' },
          { name: 'Battery', value: 'Up to 9 hours continuous gameplay' },
        ],
        tags: ['nintendo', 'switch', 'oled', 'gaming', 'handheld'],
        isOrganic: false,
        isFeatured: false,
        isFlashSale: false,
        rating: 4.88,
        numReviews: 61,
        unit: 'box',
      },

      // 43. Samsung Galaxy S24 Ultra 5G
      {
        vendor: vendor2._id,
        title: 'Samsung Galaxy S24 Ultra 5G (12GB RAM, 256GB Titanium Gray)',
        banglaTitle: 'স্যামসাং গ্যালাক্সি এস২৪ আল্ট্রা ৫জি (১২ জিবি র্যাম, ২৫৬ জিবি)',
        slug: 'samsung-galaxy-s24-ultra-5g',
        shortDescription: 'Snapdragon 8 Gen 3 for Galaxy, Galaxy AI Live Translate, 200MP Quad Telephoto Camera, Built-in S-Pen.',
        description: 'Titanium built Android king powered by Snapdragon 8 Gen 3, revolutionary Galaxy AI, and 2600 nits Dynamic AMOLED 2X flat display.',
        banglaDescription: '১০০% অরিজিনাল ইনটেক সিল প্যাক, গ্যালাক্সি এআই ও অফিশিয়াল ইন্টারন্যাশনাল ওয়ারেন্টি সহ।',
        category: catMap.get('smartphones-tablets'),
        categorySlug: 'smartphones-tablets',
        brand: 'Samsung',
        price: 165000,
        discountPrice: 148500,
        stock: 14,
        soldCount: 110,
        sku: 'SAMS-S24U-256-GRY',
        images: [
          'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800&auto=format&fit=crop&q=80',
        variants: [
          {
            name: 'Storage',
            options: [
              { title: '256GB', price: 148500, stock: 9 },
              { title: '512GB', price: 168000, stock: 5 },
            ],
          },
        ],
        attributes: [
          { name: 'Camera', value: '200MP Main + 50MP 5x Optical Periscope' },
          { name: 'Display', value: '6.8" Flat QHD+ Dynamic AMOLED 2X 120Hz' },
          { name: 'Battery', value: '5000 mAh with 45W Fast Charging' },
        ],
        tags: ['samsung', 'galaxy', 's24ultra', 'flagship', 'android', 'ai'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        rating: 4.92,
        numReviews: 76,
        unit: 'box',
      },

      // 44. ASUS ROG Zephyrus G16 OLED Gaming Laptop
      {
        vendor: vendor2._id,
        title: 'ASUS ROG Zephyrus G16 OLED 240Hz (Intel Core Ultra 9 185H / RTX 4080 / 32GB / 2TB)',
        banglaTitle: 'আসুস রগ জেফায়ারাস জি১৬ ওলেড গেমিং ল্যাপটপ (আরটিএক্স ৪০৮০ / ৩২ জিবি)',
        slug: 'asus-rog-zephyrus-g16-oled',
        shortDescription: 'CNC Aluminum Chassis, 16" 2.5K OLED 240Hz 0.2ms ROG Nebula Display, Slash Lighting.',
        description: 'Ultra-thin stealth CNC aluminum gaming and AI powerhouse with RTX 4080 GPU, OLED display with 100% DCI-P3 gamut.',
        banglaDescription: 'টপ-টায়ার প্রিমিয়াম স্লিম গেমিং ও কনটেন্ট ক্রিয়েশন ওয়ার্কস্টেশন ল্যাপটপ।',
        category: catMap.get('laptops-computers'),
        categorySlug: 'laptops-computers',
        brand: 'ASUS ROG',
        price: 365000,
        discountPrice: 335000,
        stock: 4,
        soldCount: 12,
        sku: 'ASUS-ROG-G16-RTX4080',
        images: [
          'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Processor', value: 'Intel Core Ultra 9 185H (16-Core)' },
          { name: 'Graphics', value: 'NVIDIA GeForce RTX 4080 12GB GDDR6' },
          { name: 'Display', value: '16" 2.5K (2560x1600) OLED 240Hz ROG Nebula' },
        ],
        tags: ['asus', 'rog', 'laptop', 'gaming', 'rtx4080', 'oled'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.96,
        numReviews: 24,
        unit: 'box',
      },

      // 45. Marshall Stanmore III Bluetooth Speaker
      {
        vendor: vendor2._id,
        title: 'Marshall Stanmore III Bluetooth Home Speaker (Original Black & Brass)',
        banglaTitle: 'মার্শাল স্ট্যানমোর III ব্লুটুথ হোম স্পিকার (অরিজিনাল ব্ল্যাক)',
        slug: 'marshall-stanmore-iii-speaker',
        shortDescription: 'Room-filling home audio, Dynamic Loudness, Bluetooth 5.2, 3.5mm and RCA inputs, 80W output.',
        description: 'Iconic vintage Marshall aesthetic meets re-engineered wider soundstage acoustic architecture.',
        banglaDescription: 'রক অ্যান্ড রোল লেজেন্ডারি সাউন্ড ও ক্লাসিক্যাল ভিন্টেজ ডিজাইনের হোম স্পিকার।',
        category: catMap.get('electronics-gadgets'),
        categorySlug: 'electronics-gadgets',
        brand: 'Marshall',
        price: 45000,
        discountPrice: 39500,
        stock: 12,
        soldCount: 58,
        sku: 'MAR-STANMORE3-BLK',
        images: [
          'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Power Output', value: '80W Class D Amplifier' },
          { name: 'Connectivity', value: 'Bluetooth 5.2, RCA, 3.5mm Aux' },
        ],
        tags: ['marshall', 'speaker', 'audio', 'bluetooth', 'vintage', 'bass'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        rating: 4.91,
        numReviews: 44,
        unit: 'box',
      },

      // 46. Casio G-Shock CasiOak Watch
      {
        vendor: vendor2._id,
        title: 'Casio G-Shock GA-2100-1A1 "Blackout CasiOak" Carbon Core Guard Watch',
        banglaTitle: 'ক্যাসিও জি-শক GA-2100-1A1 ব্ল্যাকআউট কার্বন কোর গার্ড ঘড়ি',
        slug: 'casio-g-shock-ga-2100-casioak',
        shortDescription: '200M Water Resistance, Carbon Core Guard Structure, Double LED Light, World Time.',
        description: 'The viral slim octagonal minimalist iconic G-Shock crafted with carbon fiber reinforced resin.',
        banglaDescription: '১০০% অরিজিনাল ক্যাসিও ইন্টারন্যাশনাল ২ বছরের অফিসিয়াল ওয়ারেন্টি কার্ড সহ।',
        category: catMap.get('watches-accessories'),
        categorySlug: 'watches-accessories',
        brand: 'Casio G-Shock',
        price: 14500,
        discountPrice: 12200,
        stock: 25,
        soldCount: 180,
        sku: 'CASIO-GA2100-1A1',
        images: [
          'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Water Resistance', value: '200 Meters (20 Bar)' },
          { name: 'Structure', value: 'Carbon Core Guard Shock Resistant' },
        ],
        tags: ['casio', 'gshock', 'casioak', 'watch', 'blackout', 'men'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.89,
        numReviews: 120,
        unit: 'box',
      },

      // 47. Organic Cold-Pressed Wood Ghani Mustard Oil (5L)
      {
        vendor: vendor1._id,
        title: 'ShopX Organic Cold-Pressed Wood Ghani Mustard Oil (সরিষার তেল - ৫ লিটার ক্যান)',
        banglaTitle: 'খাঁটি কাঠের ঘানি ভাঙা দেশি সরিষার তেল (৫ লিটার ফুড-গ্রেড ক্যান)',
        slug: 'pure-cold-pressed-mustard-oil-5l',
        shortDescription: '100% Pure, Unrefined, Cold Pressed from select indigenous Maghi Mustard seeds.',
        description: 'Cold pressed at low temperatures without any chemicals to preserve pungent aroma, natural antioxidants, and omega-3 fatty acids.',
        banglaDescription: 'মাঘী সরিষা থেকে দেশীয় কাঠের ঘানিতে কম তাপে ভাঙানো শতভাগ খাঁটি ও তীব্র ঝাঁঝালো সরিষার তেল।',
        category: catMap.get('organic-foods'),
        categorySlug: 'organic-foods',
        brand: 'ShopX Pure Organics',
        price: 1750,
        discountPrice: 1490,
        stock: 50,
        soldCount: 340,
        sku: 'SX-MUSTARD-OIL-5L',
        images: [
          'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Extraction Method', value: 'Traditional Wood Ghani (Cold Pressed)' },
          { name: 'Purity Certificate', value: 'BSTI & Lab Tested Zero Paraffin' },
        ],
        tags: ['mustard', 'oil', 'organic', 'ghani', 'sorisha', 'pure', 'cooking'],
        isOrganic: true,
        isFeatured: true,
        isFlashSale: true,
        rating: 4.96,
        numReviews: 215,
        unit: 'can',
      },

      // 48. Pure Virgin Kalijira Oil
      {
        vendor: vendor1._id,
        title: 'Organic 100% Pure Virgin Black Seed Oil (কালোজিরা তেল - ২৫০ মিলি)',
        banglaTitle: '১০০% খাঁটি কোল্ড-প্রেসড কালোজিরা তেল (২৫০ মিলি গ্লাস বোটল)',
        slug: 'pure-virgin-kalijira-oil-250ml',
        shortDescription: 'First Cold Press of Nigella Sativa seeds, high Thymoquinone potency for immunity.',
        description: 'Immunity powerhouse extracted through single cold press extraction, free from fillers or carrier oils.',
        banglaDescription: 'রোগ প্রতিরোধ ক্ষমতা বৃদ্ধিতে প্রথম কোল্ড প্রেসে তৈরি বিশুদ্ধ কালোজিরা তেল।',
        category: catMap.get('organic-foods'),
        categorySlug: 'organic-foods',
        brand: 'ShopX Pure Organics',
        price: 750,
        discountPrice: 620,
        stock: 75,
        soldCount: 420,
        sku: 'SX-KALIJIRA-OIL-250ML',
        images: [
          'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Active Compound', value: 'Rich in Natural Thymoquinone (TQ)' },
          { name: 'Extraction', value: '100% First Cold Press Single Origin' },
        ],
        tags: ['kalijira', 'blackseed', 'oil', 'health', 'immunity', 'organic'],
        isOrganic: true,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.98,
        numReviews: 310,
        unit: 'bottle',
      },

      // 49. Organic Chia Seeds 500g
      {
        vendor: vendor1._id,
        title: 'Organic High-Fiber Black Chia Seeds (প্রিমিয়াম অর্গানিক চিয়া সিড - ৫০০ গ্রাম)',
        banglaTitle: 'প্রিমিয়াম অর্গানিক ব্ল্যাক চিয়া সিড (৫০০ গ্রাম এয়ারটাইট জার)',
        slug: 'organic-black-chia-seeds-500g',
        shortDescription: 'Raw, unrefined, pesticide-free superfood loaded with Omega-3, fiber, and protein.',
        description: 'Nutrient-dense organic superfood seed perfect for weight management smoothies, puddings, and detox drinks.',
        banglaDescription: 'ওজন নিয়ন্ত্রণ ও হার্টের সুস্থতায় প্রাকৃতিক পুষ্টিগুণ সমৃদ্ধ অর্গানিক চিয়া সিড।',
        category: catMap.get('organic-foods'),
        categorySlug: 'organic-foods',
        brand: 'ShopX Pure Organics',
        price: 550,
        discountPrice: 450,
        stock: 90,
        soldCount: 580,
        sku: 'SX-CHIA-SEEDS-500G',
        images: [
          'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1514733670139-4d87a1941d55?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Nutrition', value: 'High Omega-3, Dietary Fiber & Plant Protein' },
          { name: 'Origin', value: 'Certified Organic Harvest' },
        ],
        tags: ['chia', 'seeds', 'organic', 'superfood', 'diet', 'weightloss'],
        isOrganic: true,
        isFeatured: false,
        isFlashSale: true,
        rating: 4.9,
        numReviews: 190,
        unit: 'jar',
      },

      // 50. Handwoven Dhakai Jamdani Saree
      {
        vendor: vendor3._id,
        title: 'Traditional Handloom Dhakai Jamdani Silk Saree (84 Count Heritage Motif)',
        banglaTitle: 'ঐতিহ্যবাহী হাতে বোনা ৮৪ কাউন্ট ঢাকাই জামদানি সিল্ক শাড়ি',
        slug: 'traditional-dhakai-jamdani-saree-84count',
        shortDescription: 'Hand-woven over 45 days by master artisans in Narayanganj with intricate golden zari florals.',
        description: 'Masterpiece of Bangladeshi textile heritage, featherlight, breathable, and woven with generational weaving precision.',
        banglaDescription: 'রূপগঞ্জের দক্ষ কারিগরদের হাতে তৈরি আসল ৮৪ কাউন্টের অভিজাত ঢাকাই জামদানি।',
        category: catMap.get('fashion-lifestyle'),
        categorySlug: 'fashion-lifestyle',
        brand: 'Heritage Weaves BD',
        price: 15500,
        discountPrice: 12800,
        stock: 12,
        soldCount: 75,
        sku: 'HW-JAMDANI-84C',
        images: [
          'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Weave Count', value: '84 Count Superfine Cotton Silk' },
          { name: 'Length', value: '12 Haat with Unstitched Blouse Piece' },
        ],
        tags: ['saree', 'jamdani', 'dhakai', 'handloom', 'heritage', 'silk', 'women'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.97,
        numReviews: 64,
        unit: 'piece',
      },

      // 51. Genuine Leather Executive Laptop Messenger Bag
      {
        vendor: vendor3._id,
        title: 'ShopX Artisanal Full-Grain Vintage Cow Leather Laptop Messenger Bag (15.6")',
        banglaTitle: 'আর্টিসানাল খাঁটি চামড়ার এক্সিকিউটিভ ল্যাপটপ মেসেঞ্জার ব্যাগ (১৫.৬ ইঞ্চি)',
        slug: 'full-grain-leather-laptop-messenger-bag',
        shortDescription: '100% Genuine Full Grain Bangladeshi Leather, YKK Brass Zippers, Padded 15.6" Laptop Sleeve.',
        description: 'Heirloom quality handcrafted leather briefcase with dedicated tablet compartment, brass hardware, and lifetime leather guarantee.',
        banglaDescription: 'বাংলাদেশের সেরা ট্যানারির ফুল গ্রেইন লেদারে হাতে তৈরি দীর্ঘস্থায়ী অভিজাত অফিস ব্যাগ।',
        category: catMap.get('fashion-lifestyle'),
        categorySlug: 'fashion-lifestyle',
        brand: 'ShopX Leathercraft',
        price: 6500,
        discountPrice: 5200,
        stock: 22,
        soldCount: 165,
        sku: 'SX-LEATHER-BAG-15',
        images: [
          'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Material', value: '100% Genuine Full-Grain Vegetable Tanned Leather' },
          { name: 'Hardware', value: 'Antique Solid Brass & YKK Zippers' },
        ],
        tags: ['leather', 'bag', 'laptopbag', 'messenger', 'office', 'executive'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: true,
        rating: 4.93,
        numReviews: 112,
        unit: 'piece',
      },

      // 52. Dyson Airwrap Multi-Styler Complete Long
      {
        vendor: vendor2._id,
        title: 'Dyson Airwrap Multi-Styler Complete Long (Special Edition Strawberry Bronze and Blush Pink)',
        banglaTitle: 'ডাইসন এয়ারর‍্যাপ মাল্টি-স্টাইলার কমপ্লিট লং (স্ট্রবেরি ব্রোঞ্জ)',
        slug: 'dyson-airwrap-multi-styler-complete-long',
        shortDescription: 'Coanda airflow styling with no extreme heat, dries, curls, shapes and hides flyaways.',
        description: 'Engineered for multiple hair types and lengths, utilizes intelligent heat control to measure airflow temperature over 40 times a second.',
        banglaDescription: 'চুলের কোনো ক্ষতি ছাড়া পার্লারের মতো হেয়ার স্টাইলিংয়ের জন্য ডাইসনের অফিশিয়াল মাল্টি-স্টাইলার।',
        category: catMap.get('beauty-care'),
        categorySlug: 'beauty-care',
        brand: 'Dyson',
        price: 72000,
        discountPrice: 64500,
        stock: 7,
        soldCount: 35,
        sku: 'DYS-AIRWRAP-LNG',
        images: [
          'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Technology', value: 'Coanda Airflow with Intelligent Heat Control' },
          { name: 'Warranty', value: '2-Year Dyson International Warranty' },
        ],
        tags: ['dyson', 'airwrap', 'hair', 'beauty', 'styler', 'luxury'],
        isOrganic: false,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.97,
        numReviews: 39,
        unit: 'box',
      },

      // 53. Philips Digital Airfryer XXL 7.2L
      {
        vendor: vendor2._id,
        title: 'Philips 5000 Series Connected Digital Airfryer XXL (7.2L / 1.4kg Capacity)',
        banglaTitle: 'ফিলিপস ডিজিটাল এয়ার ফ্রায়ার XXL (৭.২ লিটার / অ্যাপ কানেক্টেড)',
        slug: 'philips-digital-airfryer-xxl-7l',
        shortDescription: 'Rapid Air Technology, 16-in-1 cooking functions, NutriU app connected, up to 90% less fat.',
        description: 'Family size 7.2-liter air fryer that allows fry, bake, grill, roast and reheat with little to no added oil.',
        banglaDescription: 'তেল ছাড়া সুস্বাদু ও পুষ্টিকর রান্নার জন্য ফিলিপসের সবচেয়ে বড় সাইজের ডিজিটাল এয়ার ফ্রায়ার।',
        category: catMap.get('home-kitchen'),
        categorySlug: 'home-kitchen',
        brand: 'Philips',
        price: 27500,
        discountPrice: 22900,
        stock: 18,
        soldCount: 98,
        sku: 'PHI-AIRFRYER-XXL',
        images: [
          'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Capacity', value: '7.2 Liters (1.4kg Food)' },
          { name: 'Features', value: 'Rapid Air, Touchscreen, 16 Cooking Programs' },
        ],
        tags: ['philips', 'airfryer', 'kitchen', 'healthy', 'home', 'appliance'],
        isOrganic: false,
        isFeatured: false,
        isFlashSale: true,
        rating: 4.88,
        numReviews: 73,
        unit: 'box',
      },

      // 54. Japanese Ceremonial Grade Matcha Green Tea
      {
        vendor: vendor2._id,
        title: 'Uji Kyoto 100% First-Harvest Ceremonial Grade Japanese Matcha (100g Tin)',
        banglaTitle: 'জাপানের উজি কিয়োটো ১০০% ফার্স্ট-হার্ভেস্ট সেরিমোনিয়াল গ্রিন টি মাচা (১০০ গ্রাম)',
        slug: 'uji-kyoto-ceremonial-matcha-100g',
        shortDescription: 'Shade-grown stone ground vibrant green tencha leaves from Uji, Kyoto with high L-theanine.',
        description: 'Authentic imported Japanese ceremonial matcha with silky texture, rich umami sweetness, and sustained clean focus.',
        banglaDescription: 'জাপান থেকে সরাসরি আমদানিকৃত ১০০% আসল স্টোন-গ্রাউন্ড সেরিমোনিয়াল মাচা পাউডার।',
        category: catMap.get('global-imports'),
        categorySlug: 'global-imports',
        brand: 'Uji Kyoto Imports',
        price: 3200,
        discountPrice: 2650,
        stock: 35,
        soldCount: 140,
        sku: 'UJI-MATCHA-100G',
        images: [
          'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=80',
        ],
        thumbnail: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=80',
        variants: [],
        attributes: [
          { name: 'Grade', value: '100% First Harvest Ceremonial Grade' },
          { name: 'Origin', value: 'Uji, Kyoto Prefecture, Japan' },
        ],
        tags: ['matcha', 'tea', 'japan', 'antioxidant', 'focus', 'organic', 'import'],
        isOrganic: true,
        isFeatured: true,
        isFlashSale: false,
        rating: 4.95,
        numReviews: 88,
        unit: 'tin',
      },
    ];

    await Product.insertMany(productsData);
    console.log(`📦 Seeded ${productsData.length} rich global & local flagship products`);

    // 5. Seed Coupons
    await Coupon.insertMany([
      {
        code: 'SHOPX100',
        discountType: 'fixed',
        discountAmount: 100,
        minOrderAmount: 1000,
        validUntil: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
        isActive: true,
      },
      {
        code: 'EID50',
        discountType: 'percentage',
        discountAmount: 10,
        minOrderAmount: 500,
        maxDiscount: 200,
        validUntil: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        isActive: true,
      },
      {
        code: 'LUCKY250',
        discountType: 'fixed',
        discountAmount: 250,
        minOrderAmount: 1500,
        validUntil: new Date(Date.now() + 180 * 24 * 60 * 60 * 1000),
        isActive: true,
      },
      {
        code: 'WELCOME50',
        discountType: 'fixed',
        discountAmount: 50,
        minOrderAmount: 400,
        validUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000),
        isActive: true,
      },
    ]);
    console.log('🏷️ Seeded coupons');

    // 6. Seed Demo Rider
    const riderUser = await User.create({
      name: 'Kamrul Hasan (Rider)',
      email: 'rider@shopxbd.com',
      phone: '01711223344',
      password: 'Password@123',
      role: 'rider',
      isVerified: true,
    });

    await Rider.create({
      user: riderUser._id,
      name: 'Kamrul Hasan',
      phone: '01711223344',
      vehicleType: 'bike',
      vehicleNumber: 'Dhaka Metro HA-4491',
      currentLocation: {
        lat: 23.8103,
        lng: 90.4125,
        address: 'Gulshan 2, Dhaka',
        lastUpdated: new Date(),
      },
      isOnline: true,
      completedDeliveries: 342,
      rating: 4.9,
    });
    console.log('🛵 Seeded demo rider');

    console.log('🎉 [ShopX BD] Global Database seeding completed successfully!');
    process.exit(0);
  } catch (error: any) {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  }
};

seedDatabase();
